package model.common;

import java.sql.Timestamp;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Jan 27 15:08:55 PKT 2019
// ---------------------------------------------------------------------
public interface VOAPP extends ApplicationModule {
    void CallAMTaskFlowActivity(int Task, String userName, String sessionID);

    void execINSERTUSERLOG(String pSessionId, String pUserName, int pAuthF, int pAuthReason);

    int execPLSQLCheckLoginAttempts(String aStringParam);

    void execUpdateUserLOG(String pSessionId, String pUserName, int pOutReason);

    String get_Spell_number(Number n);

    String execGetRetailRate(Long ProductID, Timestamp RetailRateDate);


    Timestamp execTruncDate(Timestamp InputCompDate);

    Timestamp getSelectedDate();

    String execGetRetailRateInvoic(Long ProductID, Long InvoicheadID);
}

