package model;

import java.math.BigDecimal;

import java.math.RoundingMode;

import java.sql.Timestamp;

import oracle.jbo.ApplicationModule;
import oracle.jbo.RowSet;
import oracle.jbo.domain.DBSequence;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Jun 07 03:34:51 PKT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DataLoaderSaleDiscViewRowImpl extends ViewRowImpl {
    public static final int ENTITY_DATALOADERSALEDISC = 0;
    public static final int ENTITY_CHARTOFACCOUNTS = 1;
    public static final int ENTITY_CHARTOFACCOUNTS1 = 2;
    public static final int ENTITY_VEHICLE1 = 3;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        DlsdId,
        DlsdDate,
        DlsdDactIdFk,
        DlsdCactIdFk,
        DlsdQty,
        DlsdRate,
        DlsdAmount,
        DlsdDiscRate,
        DlsdDiscAmount,
        DlsdVehicleIdFk,
        DlsdInfo,
        DlsdSlipDate,
        DlsdSlipNo,
        CoaName,
        CoaActNumber,
        CoaName1,
        CoaActNumber1,
        VehicleRegNo,
        VehicleId,
        COA_PARTY_CUSTOMER_CASH1,
        COAPRoductRevenue1,
        Vehicle1View1;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int DLSDID = AttributesEnum.DlsdId.index();
    public static final int DLSDDATE = AttributesEnum.DlsdDate.index();
    public static final int DLSDDACTIDFK = AttributesEnum.DlsdDactIdFk.index();
    public static final int DLSDCACTIDFK = AttributesEnum.DlsdCactIdFk.index();
    public static final int DLSDQTY = AttributesEnum.DlsdQty.index();
    public static final int DLSDRATE = AttributesEnum.DlsdRate.index();
    public static final int DLSDAMOUNT = AttributesEnum.DlsdAmount.index();
    public static final int DLSDDISCRATE = AttributesEnum.DlsdDiscRate.index();
    public static final int DLSDDISCAMOUNT = AttributesEnum.DlsdDiscAmount.index();
    public static final int DLSDVEHICLEIDFK = AttributesEnum.DlsdVehicleIdFk.index();
    public static final int DLSDINFO = AttributesEnum.DlsdInfo.index();
    public static final int DLSDSLIPDATE = AttributesEnum.DlsdSlipDate.index();
    public static final int DLSDSLIPNO = AttributesEnum.DlsdSlipNo.index();
    public static final int COANAME = AttributesEnum.CoaName.index();
    public static final int COAACTNUMBER = AttributesEnum.CoaActNumber.index();
    public static final int COANAME1 = AttributesEnum.CoaName1.index();
    public static final int COAACTNUMBER1 = AttributesEnum.CoaActNumber1.index();
    public static final int VEHICLEREGNO = AttributesEnum.VehicleRegNo.index();
    public static final int VEHICLEID = AttributesEnum.VehicleId.index();
    public static final int COA_PARTY_CUSTOMER_CASH1 = AttributesEnum.COA_PARTY_CUSTOMER_CASH1.index();
    public static final int COAPRODUCTREVENUE1 = AttributesEnum.COAPRoductRevenue1.index();
    public static final int VEHICLE1VIEW1 = AttributesEnum.Vehicle1View1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public DataLoaderSaleDiscViewRowImpl() {
    }

    /**
     * Gets DataLoaderSaleDisc entity object.
     * @return the DataLoaderSaleDisc
     */
    public EntityImpl getDataLoaderSaleDisc() {
        return (EntityImpl) getEntity(ENTITY_DATALOADERSALEDISC);
    }

    /**
     * Gets ChartOfAccounts entity object.
     * @return the ChartOfAccounts
     */
    public EntityImpl getChartOfAccounts() {
        return (EntityImpl) getEntity(ENTITY_CHARTOFACCOUNTS);
    }

    /**
     * Gets ChartOfAccounts1 entity object.
     * @return the ChartOfAccounts1
     */
    public EntityImpl getChartOfAccounts1() {
        return (EntityImpl) getEntity(ENTITY_CHARTOFACCOUNTS1);
    }

    /**
     * Gets Vehicle1 entity object.
     * @return the Vehicle1
     */
    public EntityImpl getVehicle1() {
        return (EntityImpl) getEntity(ENTITY_VEHICLE1);
    }

    /**
     * Gets the attribute value for DLSD_ID using the alias name DlsdId.
     * @return the DLSD_ID
     */
    public DBSequence getDlsdId() {
        return (DBSequence) getAttributeInternal(DLSDID);
    }

    /**
     * Sets <code>value</code> as attribute value for DLSD_ID using the alias name DlsdId.
     * @param value value to set the DLSD_ID
     */
    public void setDlsdId(DBSequence value) {
        setAttributeInternal(DLSDID, value);
    }

    /**
     * Gets the attribute value for DLSD_DATE using the alias name DlsdDate.
     * @return the DLSD_DATE
     */
    public Timestamp getDlsdDate() {
        return (Timestamp) getAttributeInternal(DLSDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for DLSD_DATE using the alias name DlsdDate.
     * @param value value to set the DLSD_DATE
     */
    public void setDlsdDate(Timestamp value) {
        setAttributeInternal(DLSDDATE, value);
        setAttributeInternal(DLSDSLIPDATE, value);
    }

    /**
     * Gets the attribute value for DLSD_DACT_ID_FK using the alias name DlsdDactIdFk.
     * @return the DLSD_DACT_ID_FK
     */
    public Long getDlsdDactIdFk() {
        return (Long) getAttributeInternal(DLSDDACTIDFK);
    }

    /**
     * Sets <code>value</code> as attribute value for DLSD_DACT_ID_FK using the alias name DlsdDactIdFk.
     * @param value value to set the DLSD_DACT_ID_FK
     */
    public void setDlsdDactIdFk(Long value) {
        setAttributeInternal(DLSDDACTIDFK, value);
    }

    /**
     * Gets the attribute value for DLSD_CACT_ID_FK using the alias name DlsdCactIdFk.
     * @return the DLSD_CACT_ID_FK
     */
    public Long getDlsdCactIdFk() {
        return (Long) getAttributeInternal(DLSDCACTIDFK);
    }

    /**
     * Sets <code>value</code> as attribute value for DLSD_CACT_ID_FK using the alias name DlsdCactIdFk.
     * @param value value to set the DLSD_CACT_ID_FK
     */
    public void setDlsdCactIdFk(Long value) {
        setAttributeInternal(DLSDCACTIDFK, value);
    }

    /**
     * Gets the attribute value for DLSD_QTY using the alias name DlsdQty.
     * @return the DLSD_QTY
     */
    public BigDecimal getDlsdQty() {
        
        return (BigDecimal) getAttributeInternal(DLSDQTY);
    }

    /**
     * Sets <code>value</code> as attribute value for DLSD_QTY using the alias name DlsdQty.
     * @param value value to set the DLSD_QTY
     */
    public void setDlsdQty(BigDecimal value) {
        
        setAttributeInternal(DLSDQTY, value);
        Timestamp RDate= this.getDlsdDate();
        Long productID =this.getDlsdCactIdFk();
        productID=productID-5000000;
        String rate=this.execRetailRate(productID, RDate);
            setAttributeInternal(DLSDRATE, rate);
        this.calculateAmount1();
        
     
       
          
        this.calculateAmount2();
       
    }

    /**
     * Gets the attribute value for DLSD_RATE using the alias name DlsdRate.
     * @return the DLSD_RATE
     */
    public String getDlsdRate() {
        return (String) getAttributeInternal(DLSDRATE);
    }

    /**
     * Sets <code>value</code> as attribute value for DLSD_RATE using the alias name DlsdRate.
     * @param value value to set the DLSD_RATE
     */
    public void setDlsdRate(String value) {
        setAttributeInternal(DLSDRATE, value);
    }

    /**
     * Gets the attribute value for DLSD_AMOUNT using the alias name DlsdAmount.
     * @return the DLSD_AMOUNT
     */
    public BigDecimal getDlsdAmount() {
        return (BigDecimal) getAttributeInternal(DLSDAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for DLSD_AMOUNT using the alias name DlsdAmount.
     * @param value value to set the DLSD_AMOUNT
     */
    public void setDlsdAmount(BigDecimal value) {
        setAttributeInternal(DLSDAMOUNT, value);
    }

    /**
     * Gets the attribute value for DLSD_DISC_RATE using the alias name DlsdDiscRate.
     * @return the DLSD_DISC_RATE
     */
    public String getDlsdDiscRate() {
        return (String) getAttributeInternal(DLSDDISCRATE);
    }

    /**
     * Sets <code>value</code> as attribute value for DLSD_DISC_RATE using the alias name DlsdDiscRate.
     * @param value value to set the DLSD_DISC_RATE
     */
    public void setDlsdDiscRate(String value) {
        setAttributeInternal(DLSDDISCRATE, value);
        this.calculateAmount2();
    }

    /**
     * Gets the attribute value for DLSD_DISC_AMOUNT using the alias name DlsdDiscAmount.
     * @return the DLSD_DISC_AMOUNT
     */
    public BigDecimal getDlsdDiscAmount() {
        return (BigDecimal) getAttributeInternal(DLSDDISCAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for DLSD_DISC_AMOUNT using the alias name DlsdDiscAmount.
     * @param value value to set the DLSD_DISC_AMOUNT
     */
    public void setDlsdDiscAmount(BigDecimal value) {
        setAttributeInternal(DLSDDISCAMOUNT, value);
    }

    /**
     * Gets the attribute value for DLSD_VEHICLE_ID_FK using the alias name DlsdVehicleIdFk.
     * @return the DLSD_VEHICLE_ID_FK
     */
    public Long getDlsdVehicleIdFk() {
        return (Long) getAttributeInternal(DLSDVEHICLEIDFK);
    }

    /**
     * Sets <code>value</code> as attribute value for DLSD_VEHICLE_ID_FK using the alias name DlsdVehicleIdFk.
     * @param value value to set the DLSD_VEHICLE_ID_FK
     */
    public void setDlsdVehicleIdFk(Long value) {
        setAttributeInternal(DLSDVEHICLEIDFK, value);
    }

    /**
     * Gets the attribute value for DLSD_INFO using the alias name DlsdInfo.
     * @return the DLSD_INFO
     */
    public String getDlsdInfo() {
        return (String) getAttributeInternal(DLSDINFO);
    }

    /**
     * Sets <code>value</code> as attribute value for DLSD_INFO using the alias name DlsdInfo.
     * @param value value to set the DLSD_INFO
     */
    public void setDlsdInfo(String value) {
        setAttributeInternal(DLSDINFO, value);
    }

    /**
     * Gets the attribute value for DLSD_SLIP_DATE using the alias name DlsdSlipDate.
     * @return the DLSD_SLIP_DATE
     */
    public Timestamp getDlsdSlipDate() {
        return (Timestamp) getAttributeInternal(DLSDSLIPDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for DLSD_SLIP_DATE using the alias name DlsdSlipDate.
     * @param value value to set the DLSD_SLIP_DATE
     */
    public void setDlsdSlipDate(Timestamp value) {
        setAttributeInternal(DLSDSLIPDATE, value);
    }

    /**
     * Gets the attribute value for DLSD_SLIP_NO using the alias name DlsdSlipNo.
     * @return the DLSD_SLIP_NO
     */
    public String getDlsdSlipNo() {
        return (String) getAttributeInternal(DLSDSLIPNO);
    }

    /**
     * Sets <code>value</code> as attribute value for DLSD_SLIP_NO using the alias name DlsdSlipNo.
     * @param value value to set the DLSD_SLIP_NO
     */
    public void setDlsdSlipNo(String value) {
        setAttributeInternal(DLSDSLIPNO, value);
    }

    /**
     * Gets the attribute value for COA_NAME using the alias name CoaName.
     * @return the COA_NAME
     */
    public String getCoaName() {
        return (String) getAttributeInternal(COANAME);
    }

    /**
     * Sets <code>value</code> as attribute value for COA_NAME using the alias name CoaName.
     * @param value value to set the COA_NAME
     */
    public void setCoaName(String value) {
        setAttributeInternal(COANAME, value);
    }

    /**
     * Gets the attribute value for COA_ACT_NUMBER using the alias name CoaActNumber.
     * @return the COA_ACT_NUMBER
     */
    public Long getCoaActNumber() {
        return (Long) getAttributeInternal(COAACTNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for COA_ACT_NUMBER using the alias name CoaActNumber.
     * @param value value to set the COA_ACT_NUMBER
     */
    public void setCoaActNumber(Long value) {
        setAttributeInternal(COAACTNUMBER, value);
    }

    /**
     * Gets the attribute value for COA_NAME using the alias name CoaName1.
     * @return the COA_NAME
     */
    public String getCoaName1() {
        return (String) getAttributeInternal(COANAME1);
    }

    /**
     * Sets <code>value</code> as attribute value for COA_NAME using the alias name CoaName1.
     * @param value value to set the COA_NAME
     */
    public void setCoaName1(String value) {
        setAttributeInternal(COANAME1, value);
    }

    /**
     * Gets the attribute value for COA_ACT_NUMBER using the alias name CoaActNumber1.
     * @return the COA_ACT_NUMBER
     */
    public Long getCoaActNumber1() {
        return (Long) getAttributeInternal(COAACTNUMBER1);
    }

    /**
     * Sets <code>value</code> as attribute value for COA_ACT_NUMBER using the alias name CoaActNumber1.
     * @param value value to set the COA_ACT_NUMBER
     */
    public void setCoaActNumber1(Long value) {
        setAttributeInternal(COAACTNUMBER1, value);
    }

    /**
     * Gets the attribute value for VEHICLE_REG_NO using the alias name VehicleRegNo.
     * @return the VEHICLE_REG_NO
     */
    public String getVehicleRegNo() {
        return (String) getAttributeInternal(VEHICLEREGNO);
    }

    /**
     * Sets <code>value</code> as attribute value for VEHICLE_REG_NO using the alias name VehicleRegNo.
     * @param value value to set the VEHICLE_REG_NO
     */
    public void setVehicleRegNo(String value) {
        setAttributeInternal(VEHICLEREGNO, value);
    }

    /**
     * Gets the attribute value for VEHICLE_ID using the alias name VehicleId.
     * @return the VEHICLE_ID
     */
    public DBSequence getVehicleId() {
        return (DBSequence) getAttributeInternal(VEHICLEID);
    }

    /**
     * Sets <code>value</code> as attribute value for VEHICLE_ID using the alias name VehicleId.
     * @param value value to set the VEHICLE_ID
     */
    public void setVehicleId(DBSequence value) {
        setAttributeInternal(VEHICLEID, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> COA_PARTY_CUSTOMER_CASH1.
     */
    public RowSet getCOA_PARTY_CUSTOMER_CASH1() {
        return (RowSet) getAttributeInternal(COA_PARTY_CUSTOMER_CASH1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> COAPRoductRevenue1.
     */
    public RowSet getCOAPRoductRevenue1() {
        return (RowSet) getAttributeInternal(COAPRODUCTREVENUE1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> Vehicle1View1.
     */
    public RowSet getVehicle1View1() {
        return (RowSet) getAttributeInternal(VEHICLE1VIEW1);
    }
    
    
    public void calculateAmount1(){
                        BigDecimal value;
                        BigDecimal Rate=new BigDecimal(this.getDlsdRate());
                          value=Rate.multiply(this.getDlsdQty());  
                        value=value.setScale(4, RoundingMode.HALF_UP);
                        setAttributeInternal(DLSDAMOUNT, value);
                    }
    public void calculateAmount2(){
                        BigDecimal value;
                        
                        BigDecimal Rate=new BigDecimal(this.getDlsdDiscRate());
                          value=Rate.multiply(this.getDlsdQty());  
                        value=value.setScale(4, RoundingMode.HALF_UP);
                        setAttributeInternal(DLSDDISCAMOUNT, value);
                        
                        }
    public String execRetailRate(Long Value, Timestamp RRDate) {
        String res ="" ;
        ApplicationModule applicationModule = getApplicationModule();
        
        if (applicationModule instanceof VOAPPImpl){
            VOAPPImpl am;
            am = (VOAPPImpl) applicationModule;
            res = am.execGetRetailRate(Value,RRDate);
               
                      //pass values from current row to plsql func and get resut  
               }  
        return res;
        //return (String) getAttributeInternal(TNSSPELLAMOUNT);
    } 
    
}

