package model;

import java.math.BigDecimal;

import java.math.RoundingMode;

import java.sql.Timestamp;

import oracle.jbo.ApplicationModule;
import oracle.jbo.RowSet;
import oracle.jbo.domain.DBSequence;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Mar 09 04:28:14 PKT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class Data_Loader_Retail_viewRowImpl extends ViewRowImpl {
    public static final int ENTITY_DATALOADERRETAIL = 0;
    public static final int ENTITY_CHARTOFACCOUNTS = 1;
    public static final int ENTITY_CHARTOFACCOUNTS1 = 2;
    public static final int ENTITY_CHARTOFACCOUNTS2 = 3;
    public static final int ENTITY_VEHICLE1 = 4;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        DlrAmt1,
        DlrAmt2,
        DlrDate,
        DlrId,
        DlrPartyId,
        DlrPayAmt,
        DlrProdct1,
        DlrProdct2,
        DlrQty1,
        DlrQty2,
        DlrRate1,
        DlrRate2,
        DlrRecptAmt,
        DlrSlipNbr,
        DlrVehicleId,
        VehicleRegNo,
        VehicleId,
        CoaName,
        CoaActNumber,
        CoaName1,
        CoaActNumber1,
        CoaName2,
        CoaActNumber2,
        CoaPartyAll1,
        COAProductOnly1,
        COAProductOnly2,
        Vehicle1View1;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int DLRAMT1 = AttributesEnum.DlrAmt1.index();
    public static final int DLRAMT2 = AttributesEnum.DlrAmt2.index();
    public static final int DLRDATE = AttributesEnum.DlrDate.index();
    public static final int DLRID = AttributesEnum.DlrId.index();
    public static final int DLRPARTYID = AttributesEnum.DlrPartyId.index();
    public static final int DLRPAYAMT = AttributesEnum.DlrPayAmt.index();
    public static final int DLRPRODCT1 = AttributesEnum.DlrProdct1.index();
    public static final int DLRPRODCT2 = AttributesEnum.DlrProdct2.index();
    public static final int DLRQTY1 = AttributesEnum.DlrQty1.index();
    public static final int DLRQTY2 = AttributesEnum.DlrQty2.index();
    public static final int DLRRATE1 = AttributesEnum.DlrRate1.index();
    public static final int DLRRATE2 = AttributesEnum.DlrRate2.index();
    public static final int DLRRECPTAMT = AttributesEnum.DlrRecptAmt.index();
    public static final int DLRSLIPNBR = AttributesEnum.DlrSlipNbr.index();
    public static final int DLRVEHICLEID = AttributesEnum.DlrVehicleId.index();
    public static final int VEHICLEREGNO = AttributesEnum.VehicleRegNo.index();
    public static final int VEHICLEID = AttributesEnum.VehicleId.index();
    public static final int COANAME = AttributesEnum.CoaName.index();
    public static final int COAACTNUMBER = AttributesEnum.CoaActNumber.index();
    public static final int COANAME1 = AttributesEnum.CoaName1.index();
    public static final int COAACTNUMBER1 = AttributesEnum.CoaActNumber1.index();
    public static final int COANAME2 = AttributesEnum.CoaName2.index();
    public static final int COAACTNUMBER2 = AttributesEnum.CoaActNumber2.index();
    public static final int COAPARTYALL1 = AttributesEnum.CoaPartyAll1.index();
    public static final int COAPRODUCTONLY1 = AttributesEnum.COAProductOnly1.index();
    public static final int COAPRODUCTONLY2 = AttributesEnum.COAProductOnly2.index();
    public static final int VEHICLE1VIEW1 = AttributesEnum.Vehicle1View1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public Data_Loader_Retail_viewRowImpl() {
    }

    /**
     * Gets DataLoaderRetail entity object.
     * @return the DataLoaderRetail
     */
    public EntityImpl getDataLoaderRetail() {
        return (EntityImpl) getEntity(ENTITY_DATALOADERRETAIL);
    }

    /**
     * Gets ChartOfAccounts entity object.
     * @return the ChartOfAccounts
     */
    public EntityImpl getChartOfAccounts() {
        return (EntityImpl) getEntity(ENTITY_CHARTOFACCOUNTS);
    }

    /**
     * Gets ChartOfAccounts1 entity object.
     * @return the ChartOfAccounts1
     */
    public EntityImpl getChartOfAccounts1() {
        return (EntityImpl) getEntity(ENTITY_CHARTOFACCOUNTS1);
    }

    /**
     * Gets ChartOfAccounts2 entity object.
     * @return the ChartOfAccounts2
     */
    public EntityImpl getChartOfAccounts2() {
        return (EntityImpl) getEntity(ENTITY_CHARTOFACCOUNTS2);
    }

    /**
     * Gets Vehicle1 entity object.
     * @return the Vehicle1
     */
    public EntityImpl getVehicle1() {
        return (EntityImpl) getEntity(ENTITY_VEHICLE1);
    }

    /**
     * Gets the attribute value for DLR_AMT1 using the alias name DlrAmt1.
     * @return the DLR_AMT1
     */
    public BigDecimal getDlrAmt1() {
        return (BigDecimal) getAttributeInternal(DLRAMT1);
    }

    /**
     * Sets <code>value</code> as attribute value for DLR_AMT1 using the alias name DlrAmt1.
     * @param value value to set the DLR_AMT1
     */
    public void setDlrAmt1(BigDecimal value) {
        setAttributeInternal(DLRAMT1, value);
    }

    /**
     * Gets the attribute value for DLR_AMT2 using the alias name DlrAmt2.
     * @return the DLR_AMT2
     */
    public BigDecimal getDlrAmt2() {
        return (BigDecimal) getAttributeInternal(DLRAMT2);
    }

    /**
     * Sets <code>value</code> as attribute value for DLR_AMT2 using the alias name DlrAmt2.
     * @param value value to set the DLR_AMT2
     */
    public void setDlrAmt2(BigDecimal value) {
        setAttributeInternal(DLRAMT2, value);
    }

    /**
     * Gets the attribute value for DLR_DATE using the alias name DlrDate.
     * @return the DLR_DATE
     */
    public Timestamp getDlrDate() {
        return (Timestamp) getAttributeInternal(DLRDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for DLR_DATE using the alias name DlrDate.
     * @param value value to set the DLR_DATE
     */
    public void setDlrDate(Timestamp value) {
        setAttributeInternal(DLRDATE, value);
    }

    /**
     * Gets the attribute value for DLR_ID using the alias name DlrId.
     * @return the DLR_ID
     */
    public DBSequence getDlrId() {
        return (DBSequence) getAttributeInternal(DLRID);
    }

    /**
     * Sets <code>value</code> as attribute value for DLR_ID using the alias name DlrId.
     * @param value value to set the DLR_ID
     */
    public void setDlrId(DBSequence value) {
        setAttributeInternal(DLRID, value);
    }

    /**
     * Gets the attribute value for DLR_PARTY_ID using the alias name DlrPartyId.
     * @return the DLR_PARTY_ID
     */
    public Long getDlrPartyId() {
        return (Long) getAttributeInternal(DLRPARTYID);
    }

    /**
     * Sets <code>value</code> as attribute value for DLR_PARTY_ID using the alias name DlrPartyId.
     * @param value value to set the DLR_PARTY_ID
     */
    public void setDlrPartyId(Long value) {
        setAttributeInternal(DLRPARTYID, value);
    }

    /**
     * Gets the attribute value for DLR_PAY_AMT using the alias name DlrPayAmt.
     * @return the DLR_PAY_AMT
     */
    public BigDecimal getDlrPayAmt() {
        return (BigDecimal) getAttributeInternal(DLRPAYAMT);
    }

    /**
     * Sets <code>value</code> as attribute value for DLR_PAY_AMT using the alias name DlrPayAmt.
     * @param value value to set the DLR_PAY_AMT
     */
    public void setDlrPayAmt(BigDecimal value) {
        setAttributeInternal(DLRPAYAMT, value);
    }

    /**
     * Gets the attribute value for DLR_PRODCT1 using the alias name DlrProdct1.
     * @return the DLR_PRODCT1
     */
    public Long getDlrProdct1() {
        return (Long) getAttributeInternal(DLRPRODCT1);
    }

    /**
     * Sets <code>value</code> as attribute value for DLR_PRODCT1 using the alias name DlrProdct1.
     * @param value value to set the DLR_PRODCT1
     */
    public void setDlrProdct1(Long value) {
        setAttributeInternal(DLRPRODCT1, value);
    }

    /**
     * Gets the attribute value for DLR_PRODCT2 using the alias name DlrProdct2.
     * @return the DLR_PRODCT2
     */
    public Long getDlrProdct2() {
        return (Long) getAttributeInternal(DLRPRODCT2);
    }

    /**
     * Sets <code>value</code> as attribute value for DLR_PRODCT2 using the alias name DlrProdct2.
     * @param value value to set the DLR_PRODCT2
     */
    public void setDlrProdct2(Long value) {
        setAttributeInternal(DLRPRODCT2, value);
    }

    /**
     * Gets the attribute value for DLR_QTY1 using the alias name DlrQty1.
     * @return the DLR_QTY1
     */
    public BigDecimal getDlrQty1() {
        return (BigDecimal) getAttributeInternal(DLRQTY1);
    }

    /**
     * Sets <code>value</code> as attribute value for DLR_QTY1 using the alias name DlrQty1.
     * @param value value to set the DLR_QTY1
     */
    public void setDlrQty1(BigDecimal value) {
        setAttributeInternal(DLRQTY1, value);
        Timestamp RDate= this.getDlrDate();
        Long productID =this.getDlrProdct1();
           
        String rate=this.execRetailRate(productID, RDate);
            setAttributeInternal(DLRRATE1, rate);
        this.calculateAmount1();
    }

    /**
     * Gets the attribute value for DLR_QTY2 using the alias name DlrQty2.
     * @return the DLR_QTY2
     */
    public BigDecimal getDlrQty2() {
        return (BigDecimal) getAttributeInternal(DLRQTY2);
    }

    /**
     * Sets <code>value</code> as attribute value for DLR_QTY2 using the alias name DlrQty2.
     * @param value value to set the DLR_QTY2
     */
    public void setDlrQty2(BigDecimal value) {
        setAttributeInternal(DLRQTY2, value);
        Timestamp RDate= this.getDlrDate();
        Long productID =this.getDlrProdct2();
           
        String rate=this.execRetailRate(productID, RDate);
            setAttributeInternal(DLRRATE2, rate);
        this.calculateAmount2();
    }

    /**
     * Gets the attribute value for DLR_RATE1 using the alias name DlrRate1.
     * @return the DLR_RATE1
     */
    public String getDlrRate1() {
        return (String) getAttributeInternal(DLRRATE1);
    }

    /**
     * Sets <code>value</code> as attribute value for DLR_RATE1 using the alias name DlrRate1.
     * @param value value to set the DLR_RATE1
     */
    public void setDlrRate1(String value) {
        setAttributeInternal(DLRRATE1, value);
    }

    /**
     * Gets the attribute value for DLR_RATE2 using the alias name DlrRate2.
     * @return the DLR_RATE2
     */
    public String getDlrRate2() {
        return (String) getAttributeInternal(DLRRATE2);
    }

    /**
     * Sets <code>value</code> as attribute value for DLR_RATE2 using the alias name DlrRate2.
     * @param value value to set the DLR_RATE2
     */
    public void setDlrRate2(String value) {
        setAttributeInternal(DLRRATE2, value);
    }

    /**
     * Gets the attribute value for DLR_RECPT_AMT using the alias name DlrRecptAmt.
     * @return the DLR_RECPT_AMT
     */
    public BigDecimal getDlrRecptAmt() {
        return (BigDecimal) getAttributeInternal(DLRRECPTAMT);
    }

    /**
     * Sets <code>value</code> as attribute value for DLR_RECPT_AMT using the alias name DlrRecptAmt.
     * @param value value to set the DLR_RECPT_AMT
     */
    public void setDlrRecptAmt(BigDecimal value) {
        setAttributeInternal(DLRRECPTAMT, value);
    }

    /**
     * Gets the attribute value for DLR_SLIP_NBR using the alias name DlrSlipNbr.
     * @return the DLR_SLIP_NBR
     */
    public String getDlrSlipNbr() {
        return (String) getAttributeInternal(DLRSLIPNBR);
    }

    /**
     * Sets <code>value</code> as attribute value for DLR_SLIP_NBR using the alias name DlrSlipNbr.
     * @param value value to set the DLR_SLIP_NBR
     */
    public void setDlrSlipNbr(String value) {
        setAttributeInternal(DLRSLIPNBR, value);
    }

    /**
     * Gets the attribute value for DLR_VEHICLE_ID using the alias name DlrVehicleId.
     * @return the DLR_VEHICLE_ID
     */
    public Long getDlrVehicleId() {
        return (Long) getAttributeInternal(DLRVEHICLEID);
    }

    /**
     * Sets <code>value</code> as attribute value for DLR_VEHICLE_ID using the alias name DlrVehicleId.
     * @param value value to set the DLR_VEHICLE_ID
     */
    public void setDlrVehicleId(Long value) {
        setAttributeInternal(DLRVEHICLEID, value);
    }

    /**
     * Gets the attribute value for VEHICLE_REG_NO using the alias name VehicleRegNo.
     * @return the VEHICLE_REG_NO
     */
    public String getVehicleRegNo() {
        return (String) getAttributeInternal(VEHICLEREGNO);
    }

    /**
     * Sets <code>value</code> as attribute value for VEHICLE_REG_NO using the alias name VehicleRegNo.
     * @param value value to set the VEHICLE_REG_NO
     */
    public void setVehicleRegNo(String value) {
        setAttributeInternal(VEHICLEREGNO, value);
    }

    /**
     * Gets the attribute value for VEHICLE_ID using the alias name VehicleId.
     * @return the VEHICLE_ID
     */
    public DBSequence getVehicleId() {
        return (DBSequence) getAttributeInternal(VEHICLEID);
    }

    /**
     * Sets <code>value</code> as attribute value for VEHICLE_ID using the alias name VehicleId.
     * @param value value to set the VEHICLE_ID
     */
    public void setVehicleId(DBSequence value) {
        setAttributeInternal(VEHICLEID, value);
    }

    /**
     * Gets the attribute value for COA_NAME using the alias name CoaName.
     * @return the COA_NAME
     */
    public String getCoaName() {
        return (String) getAttributeInternal(COANAME);
    }

    /**
     * Sets <code>value</code> as attribute value for COA_NAME using the alias name CoaName.
     * @param value value to set the COA_NAME
     */
    public void setCoaName(String value) {
        setAttributeInternal(COANAME, value);
    }

    /**
     * Gets the attribute value for COA_ACT_NUMBER using the alias name CoaActNumber.
     * @return the COA_ACT_NUMBER
     */
    public Long getCoaActNumber() {
        return (Long) getAttributeInternal(COAACTNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for COA_ACT_NUMBER using the alias name CoaActNumber.
     * @param value value to set the COA_ACT_NUMBER
     */
    public void setCoaActNumber(Long value) {
        setAttributeInternal(COAACTNUMBER, value);
    }

    /**
     * Gets the attribute value for COA_NAME using the alias name CoaName1.
     * @return the COA_NAME
     */
    public String getCoaName1() {
        return (String) getAttributeInternal(COANAME1);
    }

    /**
     * Sets <code>value</code> as attribute value for COA_NAME using the alias name CoaName1.
     * @param value value to set the COA_NAME
     */
    public void setCoaName1(String value) {
        setAttributeInternal(COANAME1, value);
    }

    /**
     * Gets the attribute value for COA_ACT_NUMBER using the alias name CoaActNumber1.
     * @return the COA_ACT_NUMBER
     */
    public Long getCoaActNumber1() {
        return (Long) getAttributeInternal(COAACTNUMBER1);
    }

    /**
     * Sets <code>value</code> as attribute value for COA_ACT_NUMBER using the alias name CoaActNumber1.
     * @param value value to set the COA_ACT_NUMBER
     */
    public void setCoaActNumber1(Long value) {
        setAttributeInternal(COAACTNUMBER1, value);
    }

    /**
     * Gets the attribute value for COA_NAME using the alias name CoaName2.
     * @return the COA_NAME
     */
    public String getCoaName2() {
        return (String) getAttributeInternal(COANAME2);
    }

    /**
     * Sets <code>value</code> as attribute value for COA_NAME using the alias name CoaName2.
     * @param value value to set the COA_NAME
     */
    public void setCoaName2(String value) {
        setAttributeInternal(COANAME2, value);
    }

    /**
     * Gets the attribute value for COA_ACT_NUMBER using the alias name CoaActNumber2.
     * @return the COA_ACT_NUMBER
     */
    public Long getCoaActNumber2() {
        return (Long) getAttributeInternal(COAACTNUMBER2);
    }

    /**
     * Sets <code>value</code> as attribute value for COA_ACT_NUMBER using the alias name CoaActNumber2.
     * @param value value to set the COA_ACT_NUMBER
     */
    public void setCoaActNumber2(Long value) {
        setAttributeInternal(COAACTNUMBER2, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> CoaPartyAll1.
     */
    public RowSet getCoaPartyAll1() {
        return (RowSet) getAttributeInternal(COAPARTYALL1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> COAProductOnly1.
     */
    public RowSet getCOAProductOnly1() {
        return (RowSet) getAttributeInternal(COAPRODUCTONLY1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> COAProductOnly2.
     */
    public RowSet getCOAProductOnly2() {
        return (RowSet) getAttributeInternal(COAPRODUCTONLY2);
    }

    /**
     * Gets the view accessor <code>RowSet</code> Vehicle1View1.
     */
    public RowSet getVehicle1View1() {
        return (RowSet) getAttributeInternal(VEHICLE1VIEW1);
    }

    public void calculateAmount1(){
                        BigDecimal value;
                        BigDecimal Rate=new BigDecimal(this.getDlrRate1());
                          value=Rate.multiply(this.getDlrQty1());  
                        value=value.setScale(4, RoundingMode.HALF_UP);
                        setAttributeInternal(DLRAMT1, value);
                    }
    public void calculateAmount2(){
                        BigDecimal value;
                        
                        BigDecimal Rate=new BigDecimal(this.getDlrRate2());
                          value=Rate.multiply(this.getDlrQty2());  
                        value=value.setScale(4, RoundingMode.HALF_UP);
                        setAttributeInternal(DLRAMT2, value);
                        
                        }
    public String execRetailRate(Long Value, Timestamp RRDate) {
        String res ="" ;
        ApplicationModule applicationModule = getApplicationModule();
        
        if (applicationModule instanceof VOAPPImpl){
            VOAPPImpl am;
            am = (VOAPPImpl) applicationModule;
            res = am.execGetRetailRate(Value,RRDate);
               
                      //pass values from current row to plsql func and get resut  
               }  
        return res;
        //return (String) getAttributeInternal(TNSSPELLAMOUNT);
    }
}

