package model;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Feb 01 04:31:46 PKT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DR_CR_VIEWImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public DR_CR_VIEWImpl() {
    }
}

