package model;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.RowSet;
import oracle.jbo.domain.DBSequence;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Sep 03 17:49:49 PKT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class Gle_ForStockLedgerRowImpl extends ViewRowImpl {
    public static final int ENTITY_GENERALLEDGERENTRY = 0;
    public static final int ENTITY_CHARTOFACCOUNTS = 1;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        GleAcInTnsAcNo,
        GleAdjDate,
        GleAdjTnsChildId,
        GleAdjTnsId,
        GleAvgrate,
        GleBalance,
        GleBankName,
        GleBankNameId,
        GleBankTnsTypIdFk,
        GleBrCode,
        GleCgsFlag,
        GleCgsRate,
        GleCoaActNumber,
        GleCoaExemptSalesPurchase,
        GleCredit,
        GleCreditQty,
        GleDate,
        GleDebit,
        GleDebitBal,
        GleDebitQty,
        GleDetails,
        GleEtc,
        GleId,
        GleInfo,
        GleOilDId,
        GleOilTId,
        GleOildLoadDate,
        GleOildLoadId,
        GleOldw,
        GlePlFlag,
        GleQty,
        GleQtyBal,
        GleQtyBalance,
        GleRate,
        GleSDate,
        GleSlipDate,
        GleSlipNo,
        GleSlipUseDate,
        GleStId,
        GleTnsBankId,
        GleTnsChildIdFk,
        GleTnsId,
        GleTnsViewId,
        CoaName,
        CoaActNumber,
        CoaQtyBalance,
        CoaProductId,
        COA_Product_Fuel_Only1;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int GLEACINTNSACNO = AttributesEnum.GleAcInTnsAcNo.index();
    public static final int GLEADJDATE = AttributesEnum.GleAdjDate.index();
    public static final int GLEADJTNSCHILDID = AttributesEnum.GleAdjTnsChildId.index();
    public static final int GLEADJTNSID = AttributesEnum.GleAdjTnsId.index();
    public static final int GLEAVGRATE = AttributesEnum.GleAvgrate.index();
    public static final int GLEBALANCE = AttributesEnum.GleBalance.index();
    public static final int GLEBANKNAME = AttributesEnum.GleBankName.index();
    public static final int GLEBANKNAMEID = AttributesEnum.GleBankNameId.index();
    public static final int GLEBANKTNSTYPIDFK = AttributesEnum.GleBankTnsTypIdFk.index();
    public static final int GLEBRCODE = AttributesEnum.GleBrCode.index();
    public static final int GLECGSFLAG = AttributesEnum.GleCgsFlag.index();
    public static final int GLECGSRATE = AttributesEnum.GleCgsRate.index();
    public static final int GLECOAACTNUMBER = AttributesEnum.GleCoaActNumber.index();
    public static final int GLECOAEXEMPTSALESPURCHASE = AttributesEnum.GleCoaExemptSalesPurchase.index();
    public static final int GLECREDIT = AttributesEnum.GleCredit.index();
    public static final int GLECREDITQTY = AttributesEnum.GleCreditQty.index();
    public static final int GLEDATE = AttributesEnum.GleDate.index();
    public static final int GLEDEBIT = AttributesEnum.GleDebit.index();
    public static final int GLEDEBITBAL = AttributesEnum.GleDebitBal.index();
    public static final int GLEDEBITQTY = AttributesEnum.GleDebitQty.index();
    public static final int GLEDETAILS = AttributesEnum.GleDetails.index();
    public static final int GLEETC = AttributesEnum.GleEtc.index();
    public static final int GLEID = AttributesEnum.GleId.index();
    public static final int GLEINFO = AttributesEnum.GleInfo.index();
    public static final int GLEOILDID = AttributesEnum.GleOilDId.index();
    public static final int GLEOILTID = AttributesEnum.GleOilTId.index();
    public static final int GLEOILDLOADDATE = AttributesEnum.GleOildLoadDate.index();
    public static final int GLEOILDLOADID = AttributesEnum.GleOildLoadId.index();
    public static final int GLEOLDW = AttributesEnum.GleOldw.index();
    public static final int GLEPLFLAG = AttributesEnum.GlePlFlag.index();
    public static final int GLEQTY = AttributesEnum.GleQty.index();
    public static final int GLEQTYBAL = AttributesEnum.GleQtyBal.index();
    public static final int GLEQTYBALANCE = AttributesEnum.GleQtyBalance.index();
    public static final int GLERATE = AttributesEnum.GleRate.index();
    public static final int GLESDATE = AttributesEnum.GleSDate.index();
    public static final int GLESLIPDATE = AttributesEnum.GleSlipDate.index();
    public static final int GLESLIPNO = AttributesEnum.GleSlipNo.index();
    public static final int GLESLIPUSEDATE = AttributesEnum.GleSlipUseDate.index();
    public static final int GLESTID = AttributesEnum.GleStId.index();
    public static final int GLETNSBANKID = AttributesEnum.GleTnsBankId.index();
    public static final int GLETNSCHILDIDFK = AttributesEnum.GleTnsChildIdFk.index();
    public static final int GLETNSID = AttributesEnum.GleTnsId.index();
    public static final int GLETNSVIEWID = AttributesEnum.GleTnsViewId.index();
    public static final int COANAME = AttributesEnum.CoaName.index();
    public static final int COAACTNUMBER = AttributesEnum.CoaActNumber.index();
    public static final int COAQTYBALANCE = AttributesEnum.CoaQtyBalance.index();
    public static final int COAPRODUCTID = AttributesEnum.CoaProductId.index();
    public static final int COA_PRODUCT_FUEL_ONLY1 = AttributesEnum.COA_Product_Fuel_Only1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public Gle_ForStockLedgerRowImpl() {
    }

    /**
     * Gets GeneralLedgerEntry entity object.
     * @return the GeneralLedgerEntry
     */
    public EntityImpl getGeneralLedgerEntry() {
        return (EntityImpl) getEntity(ENTITY_GENERALLEDGERENTRY);
    }

    /**
     * Gets ChartOfAccounts entity object.
     * @return the ChartOfAccounts
     */
    public EntityImpl getChartOfAccounts() {
        return (EntityImpl) getEntity(ENTITY_CHARTOFACCOUNTS);
    }

    /**
     * Gets the attribute value for GLE_AC_IN_TNS_AC_NO using the alias name GleAcInTnsAcNo.
     * @return the GLE_AC_IN_TNS_AC_NO
     */
    public Long getGleAcInTnsAcNo() {
        return (Long) getAttributeInternal(GLEACINTNSACNO);
    }

    /**
     * Sets <code>value</code> as attribute value for GLE_AC_IN_TNS_AC_NO using the alias name GleAcInTnsAcNo.
     * @param value value to set the GLE_AC_IN_TNS_AC_NO
     */
    public void setGleAcInTnsAcNo(Long value) {
        setAttributeInternal(GLEACINTNSACNO, value);
    }

    /**
     * Gets the attribute value for GLE_ADJ_DATE using the alias name GleAdjDate.
     * @return the GLE_ADJ_DATE
     */
    public Timestamp getGleAdjDate() {
        return (Timestamp) getAttributeInternal(GLEADJDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for GLE_ADJ_DATE using the alias name GleAdjDate.
     * @param value value to set the GLE_ADJ_DATE
     */
    public void setGleAdjDate(Timestamp value) {
        setAttributeInternal(GLEADJDATE, value);
    }

    /**
     * Gets the attribute value for GLE_ADJ_TNS_CHILD_ID using the alias name GleAdjTnsChildId.
     * @return the GLE_ADJ_TNS_CHILD_ID
     */
    public Long getGleAdjTnsChildId() {
        return (Long) getAttributeInternal(GLEADJTNSCHILDID);
    }

    /**
     * Sets <code>value</code> as attribute value for GLE_ADJ_TNS_CHILD_ID using the alias name GleAdjTnsChildId.
     * @param value value to set the GLE_ADJ_TNS_CHILD_ID
     */
    public void setGleAdjTnsChildId(Long value) {
        setAttributeInternal(GLEADJTNSCHILDID, value);
    }

    /**
     * Gets the attribute value for GLE_ADJ_TNS_ID using the alias name GleAdjTnsId.
     * @return the GLE_ADJ_TNS_ID
     */
    public Long getGleAdjTnsId() {
        return (Long) getAttributeInternal(GLEADJTNSID);
    }

    /**
     * Sets <code>value</code> as attribute value for GLE_ADJ_TNS_ID using the alias name GleAdjTnsId.
     * @param value value to set the GLE_ADJ_TNS_ID
     */
    public void setGleAdjTnsId(Long value) {
        setAttributeInternal(GLEADJTNSID, value);
    }

    /**
     * Gets the attribute value for GLE_AVGRATE using the alias name GleAvgrate.
     * @return the GLE_AVGRATE
     */
    public BigDecimal getGleAvgrate() {
        return (BigDecimal) getAttributeInternal(GLEAVGRATE);
    }

    /**
     * Sets <code>value</code> as attribute value for GLE_AVGRATE using the alias name GleAvgrate.
     * @param value value to set the GLE_AVGRATE
     */
    public void setGleAvgrate(BigDecimal value) {
        setAttributeInternal(GLEAVGRATE, value);
    }

    /**
     * Gets the attribute value for GLE_BALANCE using the alias name GleBalance.
     * @return the GLE_BALANCE
     */
    public BigDecimal getGleBalance() {
        return (BigDecimal) getAttributeInternal(GLEBALANCE);
    }

    /**
     * Sets <code>value</code> as attribute value for GLE_BALANCE using the alias name GleBalance.
     * @param value value to set the GLE_BALANCE
     */
    public void setGleBalance(BigDecimal value) {
        setAttributeInternal(GLEBALANCE, value);
    }

    /**
     * Gets the attribute value for GLE_BANK_NAME using the alias name GleBankName.
     * @return the GLE_BANK_NAME
     */
    public String getGleBankName() {
        return (String) getAttributeInternal(GLEBANKNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for GLE_BANK_NAME using the alias name GleBankName.
     * @param value value to set the GLE_BANK_NAME
     */
    public void setGleBankName(String value) {
        setAttributeInternal(GLEBANKNAME, value);
    }

    /**
     * Gets the attribute value for GLE_BANK_NAME_ID using the alias name GleBankNameId.
     * @return the GLE_BANK_NAME_ID
     */
    public Long getGleBankNameId() {
        return (Long) getAttributeInternal(GLEBANKNAMEID);
    }

    /**
     * Sets <code>value</code> as attribute value for GLE_BANK_NAME_ID using the alias name GleBankNameId.
     * @param value value to set the GLE_BANK_NAME_ID
     */
    public void setGleBankNameId(Long value) {
        setAttributeInternal(GLEBANKNAMEID, value);
    }

    /**
     * Gets the attribute value for GLE_BANK_TNS_TYP_ID_FK using the alias name GleBankTnsTypIdFk.
     * @return the GLE_BANK_TNS_TYP_ID_FK
     */
    public Long getGleBankTnsTypIdFk() {
        return (Long) getAttributeInternal(GLEBANKTNSTYPIDFK);
    }

    /**
     * Sets <code>value</code> as attribute value for GLE_BANK_TNS_TYP_ID_FK using the alias name GleBankTnsTypIdFk.
     * @param value value to set the GLE_BANK_TNS_TYP_ID_FK
     */
    public void setGleBankTnsTypIdFk(Long value) {
        setAttributeInternal(GLEBANKTNSTYPIDFK, value);
    }

    /**
     * Gets the attribute value for GLE_BR_CODE using the alias name GleBrCode.
     * @return the GLE_BR_CODE
     */
    public String getGleBrCode() {
        return (String) getAttributeInternal(GLEBRCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for GLE_BR_CODE using the alias name GleBrCode.
     * @param value value to set the GLE_BR_CODE
     */
    public void setGleBrCode(String value) {
        setAttributeInternal(GLEBRCODE, value);
    }

    /**
     * Gets the attribute value for GLE_CGS_FLAG using the alias name GleCgsFlag.
     * @return the GLE_CGS_FLAG
     */
    public Long getGleCgsFlag() {
        return (Long) getAttributeInternal(GLECGSFLAG);
    }

    /**
     * Sets <code>value</code> as attribute value for GLE_CGS_FLAG using the alias name GleCgsFlag.
     * @param value value to set the GLE_CGS_FLAG
     */
    public void setGleCgsFlag(Long value) {
        setAttributeInternal(GLECGSFLAG, value);
    }

    /**
     * Gets the attribute value for GLE_CGS_RATE using the alias name GleCgsRate.
     * @return the GLE_CGS_RATE
     */
    public BigDecimal getGleCgsRate() {
        return (BigDecimal) getAttributeInternal(GLECGSRATE);
    }

    /**
     * Sets <code>value</code> as attribute value for GLE_CGS_RATE using the alias name GleCgsRate.
     * @param value value to set the GLE_CGS_RATE
     */
    public void setGleCgsRate(BigDecimal value) {
        setAttributeInternal(GLECGSRATE, value);
    }

    /**
     * Gets the attribute value for GLE_COA_ACT_NUMBER using the alias name GleCoaActNumber.
     * @return the GLE_COA_ACT_NUMBER
     */
    public Long getGleCoaActNumber() {
        return (Long) getAttributeInternal(GLECOAACTNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for GLE_COA_ACT_NUMBER using the alias name GleCoaActNumber.
     * @param value value to set the GLE_COA_ACT_NUMBER
     */
    public void setGleCoaActNumber(Long value) {
        setAttributeInternal(GLECOAACTNUMBER, value);
    }

    /**
     * Gets the attribute value for GLE_COA_EXEMPT_SALES_PURCHASE using the alias name GleCoaExemptSalesPurchase.
     * @return the GLE_COA_EXEMPT_SALES_PURCHASE
     */
    public Long getGleCoaExemptSalesPurchase() {
        return (Long) getAttributeInternal(GLECOAEXEMPTSALESPURCHASE);
    }

    /**
     * Sets <code>value</code> as attribute value for GLE_COA_EXEMPT_SALES_PURCHASE using the alias name GleCoaExemptSalesPurchase.
     * @param value value to set the GLE_COA_EXEMPT_SALES_PURCHASE
     */
    public void setGleCoaExemptSalesPurchase(Long value) {
        setAttributeInternal(GLECOAEXEMPTSALESPURCHASE, value);
    }

    /**
     * Gets the attribute value for GLE_CREDIT using the alias name GleCredit.
     * @return the GLE_CREDIT
     */
    public BigDecimal getGleCredit() {
        return (BigDecimal) getAttributeInternal(GLECREDIT);
    }

    /**
     * Sets <code>value</code> as attribute value for GLE_CREDIT using the alias name GleCredit.
     * @param value value to set the GLE_CREDIT
     */
    public void setGleCredit(BigDecimal value) {
        setAttributeInternal(GLECREDIT, value);
    }

    /**
     * Gets the attribute value for GLE_CREDIT_QTY using the alias name GleCreditQty.
     * @return the GLE_CREDIT_QTY
     */
    public BigDecimal getGleCreditQty() {
        return (BigDecimal) getAttributeInternal(GLECREDITQTY);
    }

    /**
     * Sets <code>value</code> as attribute value for GLE_CREDIT_QTY using the alias name GleCreditQty.
     * @param value value to set the GLE_CREDIT_QTY
     */
    public void setGleCreditQty(BigDecimal value) {
        setAttributeInternal(GLECREDITQTY, value);
    }

    /**
     * Gets the attribute value for GLE_DATE using the alias name GleDate.
     * @return the GLE_DATE
     */
    public Timestamp getGleDate() {
        return (Timestamp) getAttributeInternal(GLEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for GLE_DATE using the alias name GleDate.
     * @param value value to set the GLE_DATE
     */
    public void setGleDate(Timestamp value) {
        setAttributeInternal(GLEDATE, value);
    }

    /**
     * Gets the attribute value for GLE_DEBIT using the alias name GleDebit.
     * @return the GLE_DEBIT
     */
    public BigDecimal getGleDebit() {
        return (BigDecimal) getAttributeInternal(GLEDEBIT);
    }

    /**
     * Sets <code>value</code> as attribute value for GLE_DEBIT using the alias name GleDebit.
     * @param value value to set the GLE_DEBIT
     */
    public void setGleDebit(BigDecimal value) {
        setAttributeInternal(GLEDEBIT, value);
    }

    /**
     * Gets the attribute value for GLE_DEBIT_BAL using the alias name GleDebitBal.
     * @return the GLE_DEBIT_BAL
     */
    public BigDecimal getGleDebitBal() {
        return (BigDecimal) getAttributeInternal(GLEDEBITBAL);
    }

    /**
     * Sets <code>value</code> as attribute value for GLE_DEBIT_BAL using the alias name GleDebitBal.
     * @param value value to set the GLE_DEBIT_BAL
     */
    public void setGleDebitBal(BigDecimal value) {
        setAttributeInternal(GLEDEBITBAL, value);
    }

    /**
     * Gets the attribute value for GLE_DEBIT_QTY using the alias name GleDebitQty.
     * @return the GLE_DEBIT_QTY
     */
    public BigDecimal getGleDebitQty() {
        return (BigDecimal) getAttributeInternal(GLEDEBITQTY);
    }

    /**
     * Sets <code>value</code> as attribute value for GLE_DEBIT_QTY using the alias name GleDebitQty.
     * @param value value to set the GLE_DEBIT_QTY
     */
    public void setGleDebitQty(BigDecimal value) {
        setAttributeInternal(GLEDEBITQTY, value);
    }

    /**
     * Gets the attribute value for GLE_DETAILS using the alias name GleDetails.
     * @return the GLE_DETAILS
     */
    public String getGleDetails() {
        return (String) getAttributeInternal(GLEDETAILS);
    }

    /**
     * Sets <code>value</code> as attribute value for GLE_DETAILS using the alias name GleDetails.
     * @param value value to set the GLE_DETAILS
     */
    public void setGleDetails(String value) {
        setAttributeInternal(GLEDETAILS, value);
    }

    /**
     * Gets the attribute value for GLE_ETC using the alias name GleEtc.
     * @return the GLE_ETC
     */
    public String getGleEtc() {
        return (String) getAttributeInternal(GLEETC);
    }

    /**
     * Sets <code>value</code> as attribute value for GLE_ETC using the alias name GleEtc.
     * @param value value to set the GLE_ETC
     */
    public void setGleEtc(String value) {
        setAttributeInternal(GLEETC, value);
    }

    /**
     * Gets the attribute value for GLE_ID using the alias name GleId.
     * @return the GLE_ID
     */
    public DBSequence getGleId() {
        return (DBSequence) getAttributeInternal(GLEID);
    }

    /**
     * Sets <code>value</code> as attribute value for GLE_ID using the alias name GleId.
     * @param value value to set the GLE_ID
     */
    public void setGleId(DBSequence value) {
        setAttributeInternal(GLEID, value);
    }

    /**
     * Gets the attribute value for GLE_INFO using the alias name GleInfo.
     * @return the GLE_INFO
     */
    public String getGleInfo() {
        return (String) getAttributeInternal(GLEINFO);
    }

    /**
     * Sets <code>value</code> as attribute value for GLE_INFO using the alias name GleInfo.
     * @param value value to set the GLE_INFO
     */
    public void setGleInfo(String value) {
        setAttributeInternal(GLEINFO, value);
    }

    /**
     * Gets the attribute value for GLE_OIL_D_ID using the alias name GleOilDId.
     * @return the GLE_OIL_D_ID
     */
    public Long getGleOilDId() {
        return (Long) getAttributeInternal(GLEOILDID);
    }

    /**
     * Sets <code>value</code> as attribute value for GLE_OIL_D_ID using the alias name GleOilDId.
     * @param value value to set the GLE_OIL_D_ID
     */
    public void setGleOilDId(Long value) {
        setAttributeInternal(GLEOILDID, value);
    }

    /**
     * Gets the attribute value for GLE_OIL_T_ID using the alias name GleOilTId.
     * @return the GLE_OIL_T_ID
     */
    public Long getGleOilTId() {
        return (Long) getAttributeInternal(GLEOILTID);
    }

    /**
     * Sets <code>value</code> as attribute value for GLE_OIL_T_ID using the alias name GleOilTId.
     * @param value value to set the GLE_OIL_T_ID
     */
    public void setGleOilTId(Long value) {
        setAttributeInternal(GLEOILTID, value);
    }

    /**
     * Gets the attribute value for GLE_OILD_LOAD_DATE using the alias name GleOildLoadDate.
     * @return the GLE_OILD_LOAD_DATE
     */
    public Timestamp getGleOildLoadDate() {
        return (Timestamp) getAttributeInternal(GLEOILDLOADDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for GLE_OILD_LOAD_DATE using the alias name GleOildLoadDate.
     * @param value value to set the GLE_OILD_LOAD_DATE
     */
    public void setGleOildLoadDate(Timestamp value) {
        setAttributeInternal(GLEOILDLOADDATE, value);
    }

    /**
     * Gets the attribute value for GLE_OILD_LOAD_ID using the alias name GleOildLoadId.
     * @return the GLE_OILD_LOAD_ID
     */
    public Long getGleOildLoadId() {
        return (Long) getAttributeInternal(GLEOILDLOADID);
    }

    /**
     * Sets <code>value</code> as attribute value for GLE_OILD_LOAD_ID using the alias name GleOildLoadId.
     * @param value value to set the GLE_OILD_LOAD_ID
     */
    public void setGleOildLoadId(Long value) {
        setAttributeInternal(GLEOILDLOADID, value);
    }

    /**
     * Gets the attribute value for GLE_OLDW using the alias name GleOldw.
     * @return the GLE_OLDW
     */
    public Integer getGleOldw() {
        return (Integer) getAttributeInternal(GLEOLDW);
    }

    /**
     * Sets <code>value</code> as attribute value for GLE_OLDW using the alias name GleOldw.
     * @param value value to set the GLE_OLDW
     */
    public void setGleOldw(Integer value) {
        setAttributeInternal(GLEOLDW, value);
    }

    /**
     * Gets the attribute value for GLE_PL_FLAG using the alias name GlePlFlag.
     * @return the GLE_PL_FLAG
     */
    public Long getGlePlFlag() {
        return (Long) getAttributeInternal(GLEPLFLAG);
    }

    /**
     * Sets <code>value</code> as attribute value for GLE_PL_FLAG using the alias name GlePlFlag.
     * @param value value to set the GLE_PL_FLAG
     */
    public void setGlePlFlag(Long value) {
        setAttributeInternal(GLEPLFLAG, value);
    }

    /**
     * Gets the attribute value for GLE_QTY using the alias name GleQty.
     * @return the GLE_QTY
     */
    public BigDecimal getGleQty() {
        return (BigDecimal) getAttributeInternal(GLEQTY);
    }

    /**
     * Sets <code>value</code> as attribute value for GLE_QTY using the alias name GleQty.
     * @param value value to set the GLE_QTY
     */
    public void setGleQty(BigDecimal value) {
        setAttributeInternal(GLEQTY, value);
    }

    /**
     * Gets the attribute value for GLE_QTY_BAL using the alias name GleQtyBal.
     * @return the GLE_QTY_BAL
     */
    public BigDecimal getGleQtyBal() {
        return (BigDecimal) getAttributeInternal(GLEQTYBAL);
    }

    /**
     * Sets <code>value</code> as attribute value for GLE_QTY_BAL using the alias name GleQtyBal.
     * @param value value to set the GLE_QTY_BAL
     */
    public void setGleQtyBal(BigDecimal value) {
        setAttributeInternal(GLEQTYBAL, value);
    }

    /**
     * Gets the attribute value for GLE_QTY_BALANCE using the alias name GleQtyBalance.
     * @return the GLE_QTY_BALANCE
     */
    public BigDecimal getGleQtyBalance() {
        return (BigDecimal) getAttributeInternal(GLEQTYBALANCE);
    }

    /**
     * Sets <code>value</code> as attribute value for GLE_QTY_BALANCE using the alias name GleQtyBalance.
     * @param value value to set the GLE_QTY_BALANCE
     */
    public void setGleQtyBalance(BigDecimal value) {
        setAttributeInternal(GLEQTYBALANCE, value);
    }

    /**
     * Gets the attribute value for GLE_RATE using the alias name GleRate.
     * @return the GLE_RATE
     */
    public BigDecimal getGleRate() {
        return (BigDecimal) getAttributeInternal(GLERATE);
    }

    /**
     * Sets <code>value</code> as attribute value for GLE_RATE using the alias name GleRate.
     * @param value value to set the GLE_RATE
     */
    public void setGleRate(BigDecimal value) {
        setAttributeInternal(GLERATE, value);
    }

    /**
     * Gets the attribute value for GLE_S_DATE using the alias name GleSDate.
     * @return the GLE_S_DATE
     */
    public Timestamp getGleSDate() {
        return (Timestamp) getAttributeInternal(GLESDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for GLE_S_DATE using the alias name GleSDate.
     * @param value value to set the GLE_S_DATE
     */
    public void setGleSDate(Timestamp value) {
        setAttributeInternal(GLESDATE, value);
    }

    /**
     * Gets the attribute value for GLE_SLIP_DATE using the alias name GleSlipDate.
     * @return the GLE_SLIP_DATE
     */
    public Timestamp getGleSlipDate() {
        return (Timestamp) getAttributeInternal(GLESLIPDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for GLE_SLIP_DATE using the alias name GleSlipDate.
     * @param value value to set the GLE_SLIP_DATE
     */
    public void setGleSlipDate(Timestamp value) {
        setAttributeInternal(GLESLIPDATE, value);
    }

    /**
     * Gets the attribute value for GLE_SLIP_NO using the alias name GleSlipNo.
     * @return the GLE_SLIP_NO
     */
    public String getGleSlipNo() {
        return (String) getAttributeInternal(GLESLIPNO);
    }

    /**
     * Sets <code>value</code> as attribute value for GLE_SLIP_NO using the alias name GleSlipNo.
     * @param value value to set the GLE_SLIP_NO
     */
    public void setGleSlipNo(String value) {
        setAttributeInternal(GLESLIPNO, value);
    }

    /**
     * Gets the attribute value for "Synchronize:Fix_SQL" using the alias name GleSlipUseDate.
     * @return the "Synchronize:Fix_SQL"
     */
    public Timestamp getGleSlipUseDate() {
        return (Timestamp) getAttributeInternal(GLESLIPUSEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for "Synchronize:Fix_SQL" using the alias name GleSlipUseDate.
     * @param value value to set the "Synchronize:Fix_SQL"
     */
    public void setGleSlipUseDate(Timestamp value) {
        setAttributeInternal(GLESLIPUSEDATE, value);
    }

    /**
     * Gets the attribute value for GLE_ST_ID using the alias name GleStId.
     * @return the GLE_ST_ID
     */
    public Long getGleStId() {
        return (Long) getAttributeInternal(GLESTID);
    }

    /**
     * Sets <code>value</code> as attribute value for GLE_ST_ID using the alias name GleStId.
     * @param value value to set the GLE_ST_ID
     */
    public void setGleStId(Long value) {
        setAttributeInternal(GLESTID, value);
    }

    /**
     * Gets the attribute value for "Synchronize:Fix_SQL" using the alias name GleTnsBankId.
     * @return the "Synchronize:Fix_SQL"
     */
    public Long getGleTnsBankId() {
        return (Long) getAttributeInternal(GLETNSBANKID);
    }

    /**
     * Sets <code>value</code> as attribute value for "Synchronize:Fix_SQL" using the alias name GleTnsBankId.
     * @param value value to set the "Synchronize:Fix_SQL"
     */
    public void setGleTnsBankId(Long value) {
        setAttributeInternal(GLETNSBANKID, value);
    }

    /**
     * Gets the attribute value for GLE_TNS_CHILD_ID_FK using the alias name GleTnsChildIdFk.
     * @return the GLE_TNS_CHILD_ID_FK
     */
    public Long getGleTnsChildIdFk() {
        return (Long) getAttributeInternal(GLETNSCHILDIDFK);
    }

    /**
     * Sets <code>value</code> as attribute value for GLE_TNS_CHILD_ID_FK using the alias name GleTnsChildIdFk.
     * @param value value to set the GLE_TNS_CHILD_ID_FK
     */
    public void setGleTnsChildIdFk(Long value) {
        setAttributeInternal(GLETNSCHILDIDFK, value);
    }

    /**
     * Gets the attribute value for GLE_TNS_ID using the alias name GleTnsId.
     * @return the GLE_TNS_ID
     */
    public Long getGleTnsId() {
        return (Long) getAttributeInternal(GLETNSID);
    }

    /**
     * Sets <code>value</code> as attribute value for GLE_TNS_ID using the alias name GleTnsId.
     * @param value value to set the GLE_TNS_ID
     */
    public void setGleTnsId(Long value) {
        setAttributeInternal(GLETNSID, value);
    }

    /**
     * Gets the attribute value for GLE_TNS_VIEW_ID using the alias name GleTnsViewId.
     * @return the GLE_TNS_VIEW_ID
     */
    public Long getGleTnsViewId() {
        return (Long) getAttributeInternal(GLETNSVIEWID);
    }

    /**
     * Sets <code>value</code> as attribute value for GLE_TNS_VIEW_ID using the alias name GleTnsViewId.
     * @param value value to set the GLE_TNS_VIEW_ID
     */
    public void setGleTnsViewId(Long value) {
        setAttributeInternal(GLETNSVIEWID, value);
    }

    /**
     * Gets the attribute value for COA_NAME using the alias name CoaName.
     * @return the COA_NAME
     */
    public String getCoaName() {
        return (String) getAttributeInternal(COANAME);
    }

    /**
     * Sets <code>value</code> as attribute value for COA_NAME using the alias name CoaName.
     * @param value value to set the COA_NAME
     */
    public void setCoaName(String value) {
        setAttributeInternal(COANAME, value);
    }

    /**
     * Gets the attribute value for COA_ACT_NUMBER using the alias name CoaActNumber.
     * @return the COA_ACT_NUMBER
     */
    public Long getCoaActNumber() {
        return (Long) getAttributeInternal(COAACTNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for COA_ACT_NUMBER using the alias name CoaActNumber.
     * @param value value to set the COA_ACT_NUMBER
     */
    public void setCoaActNumber(Long value) {
        setAttributeInternal(COAACTNUMBER, value);
    }

    /**
     * Gets the attribute value for COA_QTY_BALANCE using the alias name CoaQtyBalance.
     * @return the COA_QTY_BALANCE
     */
    public Long getCoaQtyBalance() {
        return (Long) getAttributeInternal(COAQTYBALANCE);
    }

    /**
     * Sets <code>value</code> as attribute value for COA_QTY_BALANCE using the alias name CoaQtyBalance.
     * @param value value to set the COA_QTY_BALANCE
     */
    public void setCoaQtyBalance(Long value) {
        setAttributeInternal(COAQTYBALANCE, value);
    }

    /**
     * Gets the attribute value for COA_PRODUCT_ID using the alias name CoaProductId.
     * @return the COA_PRODUCT_ID
     */
    public Long getCoaProductId() {
        return (Long) getAttributeInternal(COAPRODUCTID);
    }

    /**
     * Sets <code>value</code> as attribute value for COA_PRODUCT_ID using the alias name CoaProductId.
     * @param value value to set the COA_PRODUCT_ID
     */
    public void setCoaProductId(Long value) {
        setAttributeInternal(COAPRODUCTID, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> COA_Product_Fuel_Only1.
     */
    public RowSet getCOA_Product_Fuel_Only1() {
        return (RowSet) getAttributeInternal(COA_PRODUCT_FUEL_ONLY1);
    }
}

