package model;

import java.sql.Timestamp;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Apr 18 01:07:07 PKT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class GleForJournalLedgerReportImpl extends ViewObjectImpl implements model.common.GleForJournalLedgerReport {
    /**
     * This is the default constructor (do not remove).
     */
    public GleForJournalLedgerReportImpl() {
    }

    /**
     * Returns the variable value for BindCoaName.
     * @return variable value for BindCoaName
     */
    public String getBindCoaName() {
        return (String) ensureVariableManager().getVariableValue("BindCoaName");
    }

    /**
     * Sets <code>value</code> for variable BindCoaName.
     * @param value value to bind as BindCoaName
     */
    public void setBindCoaName(String value) {
        ensureVariableManager().setVariableValue("BindCoaName", value);
    }

    /**
     * Returns the variable value for BindGleStartDate.
     * @return variable value for BindGleStartDate
     */
    public Timestamp getBindGleStartDate() {
        return (Timestamp) ensureVariableManager().getVariableValue("BindGleStartDate");
    }

    /**
     * Sets <code>value</code> for variable BindGleStartDate.
     * @param value value to bind as BindGleStartDate
     */
    public void setBindGleStartDate(Timestamp value) {
        ensureVariableManager().setVariableValue("BindGleStartDate", value);
    }

    /**
     * Returns the variable value for BindGleEndDate.
     * @return variable value for BindGleEndDate
     */
    public Timestamp getBindGleEndDate() {
        return (Timestamp) ensureVariableManager().getVariableValue("BindGleEndDate");
    }

    /**
     * Sets <code>value</code> for variable BindGleEndDate.
     * @param value value to bind as BindGleEndDate
     */
    public void setBindGleEndDate(Timestamp value) {
        ensureVariableManager().setVariableValue("BindGleEndDate", value);
    }
    
    public void refreshQuery(String coaName,Timestamp startDate,Timestamp endDate) {
       this.clearCache();
        this.setBindCoaName(coaName);
        this.setBindGleStartDate(startDate);
        this.setBindGleEndDate(endDate);
        this.executeQuery();
       
    }
    
}


