package model;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.RowSet;
import oracle.jbo.domain.DBSequence;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Feb 03 01:26:26 PKT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class GleForJournalLedgerReportRowImpl extends ViewRowImpl {

    public static final int ENTITY_GENERALLEDGERENTRY = 0;
    public static final int ENTITY_BANKNAME = 1;
    public static final int ENTITY_BANKTNSTYPE = 2;
    public static final int ENTITY_OILDEPO = 3;
    public static final int ENTITY_OILTANKER = 4;
    public static final int ENTITY_OILDEPO1 = 5;
    public static final int ENTITY_CHARTOFACCOUNTS = 6;
    public static final int ENTITY_CHARTOFACCOUNTS1 = 7;
    public static final int ENTITY_VEHICLE1 = 8;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        GleAcInTnsAcNo,
        GleAdjDate,
        GleAdjTnsChildId,
        GleAdjTnsId,
        GleAvgrate,
        GleBalance,
        GleBankName,
        GleBankNameId,
        GleBankTnsTypIdFk,
        GleBrCode,
        GleCgsFlag,
        GleCgsRate,
        GleCoaActNumber,
        GleCoaExemptSalesPurchase,
        GleCredit,
        GleCreditQty,
        GleDate,
        GleDebit,
        GleDebitBal,
        GleDebitQty,
        GleDetails,
        GleEtc,
        GleId,
        GleInfo,
        GleOilDId,
        GleOilTId,
        GleOildLoadDate,
        GleOildLoadId,
        GleOldw,
        GlePlFlag,
        GleQty,
        GleQtyBal,
        GleQtyBalance,
        GleRate,
        GleSDate,
        GleSlipDate,
        GleSlipNo,
        GleSlipUseDate,
        GleStId,
        GleTnsBankId,
        GleTnsChildIdFk,
        GleTnsId,
        GleTnsViewId,
        BankName1,
        BankNameId,
        BankTnsTypeName,
        BankTnsTypeId,
        OildShortname,
        OildId,
        OiltRegistration,
        OiltId,
        OildShortname1,
        OildId1,
        CoaName,
        CoaActNumber,
        CoaBalance,
        CoaName1,
        CoaActNumber1,
        VehicleIdFk,
        VehicleRegNo,
        VehicleId,
        BankNameView1,
        OIL_DEPO_WITH_NA_VIEW1,
        OilTankerAllView1,
        OIL_DEPO_WITH_NA_VIEW2,
        AppModule_CoaAllWithstatedCapital1_1,
        CoaAllWithstatedCapital1;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int GLEACINTNSACNO = AttributesEnum.GleAcInTnsAcNo.index();
    public static final int GLEADJDATE = AttributesEnum.GleAdjDate.index();
    public static final int GLEADJTNSCHILDID = AttributesEnum.GleAdjTnsChildId.index();
    public static final int GLEADJTNSID = AttributesEnum.GleAdjTnsId.index();
    public static final int GLEAVGRATE = AttributesEnum.GleAvgrate.index();
    public static final int GLEBALANCE = AttributesEnum.GleBalance.index();
    public static final int GLEBANKNAME = AttributesEnum.GleBankName.index();
    public static final int GLEBANKNAMEID = AttributesEnum.GleBankNameId.index();
    public static final int GLEBANKTNSTYPIDFK = AttributesEnum.GleBankTnsTypIdFk.index();
    public static final int GLEBRCODE = AttributesEnum.GleBrCode.index();
    public static final int GLECGSFLAG = AttributesEnum.GleCgsFlag.index();
    public static final int GLECGSRATE = AttributesEnum.GleCgsRate.index();
    public static final int GLECOAACTNUMBER = AttributesEnum.GleCoaActNumber.index();
    public static final int GLECOAEXEMPTSALESPURCHASE = AttributesEnum.GleCoaExemptSalesPurchase.index();
    public static final int GLECREDIT = AttributesEnum.GleCredit.index();
    public static final int GLECREDITQTY = AttributesEnum.GleCreditQty.index();
    public static final int GLEDATE = AttributesEnum.GleDate.index();
    public static final int GLEDEBIT = AttributesEnum.GleDebit.index();
    public static final int GLEDEBITBAL = AttributesEnum.GleDebitBal.index();
    public static final int GLEDEBITQTY = AttributesEnum.GleDebitQty.index();
    public static final int GLEDETAILS = AttributesEnum.GleDetails.index();
    public static final int GLEETC = AttributesEnum.GleEtc.index();
    public static final int GLEID = AttributesEnum.GleId.index();
    public static final int GLEINFO = AttributesEnum.GleInfo.index();
    public static final int GLEOILDID = AttributesEnum.GleOilDId.index();
    public static final int GLEOILTID = AttributesEnum.GleOilTId.index();
    public static final int GLEOILDLOADDATE = AttributesEnum.GleOildLoadDate.index();
    public static final int GLEOILDLOADID = AttributesEnum.GleOildLoadId.index();
    public static final int GLEOLDW = AttributesEnum.GleOldw.index();
    public static final int GLEPLFLAG = AttributesEnum.GlePlFlag.index();
    public static final int GLEQTY = AttributesEnum.GleQty.index();
    public static final int GLEQTYBAL = AttributesEnum.GleQtyBal.index();
    public static final int GLEQTYBALANCE = AttributesEnum.GleQtyBalance.index();
    public static final int GLERATE = AttributesEnum.GleRate.index();
    public static final int GLESDATE = AttributesEnum.GleSDate.index();
    public static final int GLESLIPDATE = AttributesEnum.GleSlipDate.index();
    public static final int GLESLIPNO = AttributesEnum.GleSlipNo.index();
    public static final int GLESLIPUSEDATE = AttributesEnum.GleSlipUseDate.index();
    public static final int GLESTID = AttributesEnum.GleStId.index();
    public static final int GLETNSBANKID = AttributesEnum.GleTnsBankId.index();
    public static final int GLETNSCHILDIDFK = AttributesEnum.GleTnsChildIdFk.index();
    public static final int GLETNSID = AttributesEnum.GleTnsId.index();
    public static final int GLETNSVIEWID = AttributesEnum.GleTnsViewId.index();
    public static final int BANKNAME1 = AttributesEnum.BankName1.index();
    public static final int BANKNAMEID = AttributesEnum.BankNameId.index();
    public static final int BANKTNSTYPENAME = AttributesEnum.BankTnsTypeName.index();
    public static final int BANKTNSTYPEID = AttributesEnum.BankTnsTypeId.index();
    public static final int OILDSHORTNAME = AttributesEnum.OildShortname.index();
    public static final int OILDID = AttributesEnum.OildId.index();
    public static final int OILTREGISTRATION = AttributesEnum.OiltRegistration.index();
    public static final int OILTID = AttributesEnum.OiltId.index();
    public static final int OILDSHORTNAME1 = AttributesEnum.OildShortname1.index();
    public static final int OILDID1 = AttributesEnum.OildId1.index();
    public static final int COANAME = AttributesEnum.CoaName.index();
    public static final int COAACTNUMBER = AttributesEnum.CoaActNumber.index();
    public static final int COABALANCE = AttributesEnum.CoaBalance.index();
    public static final int COANAME1 = AttributesEnum.CoaName1.index();
    public static final int COAACTNUMBER1 = AttributesEnum.CoaActNumber1.index();
    public static final int VEHICLEIDFK = AttributesEnum.VehicleIdFk.index();
    public static final int VEHICLEREGNO = AttributesEnum.VehicleRegNo.index();
    public static final int VEHICLEID = AttributesEnum.VehicleId.index();
    public static final int BANKNAMEVIEW1 = AttributesEnum.BankNameView1.index();
    public static final int OIL_DEPO_WITH_NA_VIEW1 = AttributesEnum.OIL_DEPO_WITH_NA_VIEW1.index();
    public static final int OILTANKERALLVIEW1 = AttributesEnum.OilTankerAllView1.index();
    public static final int OIL_DEPO_WITH_NA_VIEW2 = AttributesEnum.OIL_DEPO_WITH_NA_VIEW2.index();
    public static final int APPMODULE_COAALLWITHSTATEDCAPITAL1_1 =
        AttributesEnum.AppModule_CoaAllWithstatedCapital1_1.index();
    public static final int COAALLWITHSTATEDCAPITAL1 = AttributesEnum.CoaAllWithstatedCapital1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public GleForJournalLedgerReportRowImpl() {
    }

    /**
     * Gets GeneralLedgerEntry entity object.
     * @return the GeneralLedgerEntry
     */
    public EntityImpl getGeneralLedgerEntry() {
        return (EntityImpl) getEntity(ENTITY_GENERALLEDGERENTRY);
    }

    /**
     * Gets BankName entity object.
     * @return the BankName
     */
    public EntityImpl getBankName() {
        return (EntityImpl) getEntity(ENTITY_BANKNAME);
    }

    /**
     * Gets BankTnsType entity object.
     * @return the BankTnsType
     */
    public EntityImpl getBankTnsType() {
        return (EntityImpl) getEntity(ENTITY_BANKTNSTYPE);
    }

    /**
     * Gets OilDepo entity object.
     * @return the OilDepo
     */
    public EntityImpl getOilDepo() {
        return (EntityImpl) getEntity(ENTITY_OILDEPO);
    }

    /**
     * Gets OilTanker entity object.
     * @return the OilTanker
     */
    public EntityImpl getOilTanker() {
        return (EntityImpl) getEntity(ENTITY_OILTANKER);
    }

    /**
     * Gets OilDepo1 entity object.
     * @return the OilDepo1
     */
    public EntityImpl getOilDepo1() {
        return (EntityImpl) getEntity(ENTITY_OILDEPO1);
    }

    /**
     * Gets ChartOfAccounts entity object.
     * @return the ChartOfAccounts
     */
    public EntityImpl getChartOfAccounts() {
        return (EntityImpl) getEntity(ENTITY_CHARTOFACCOUNTS);
    }

    /**
     * Gets ChartOfAccounts1 entity object.
     * @return the ChartOfAccounts1
     */
    public EntityImpl getChartOfAccounts1() {
        return (EntityImpl) getEntity(ENTITY_CHARTOFACCOUNTS1);
    }


    /**
     * Gets Vehicle1 entity object.
     * @return the Vehicle1
     */
    public EntityImpl getVehicle1() {
        return (EntityImpl) getEntity(ENTITY_VEHICLE1);
    }

    /**
     * Gets the attribute value for GLE_AC_IN_TNS_AC_NO using the alias name GleAcInTnsAcNo.
     * @return the GLE_AC_IN_TNS_AC_NO
     */
    public Long getGleAcInTnsAcNo() {
        return (Long) getAttributeInternal(GLEACINTNSACNO);
    }

    /**
     * Gets the attribute value for GLE_ADJ_DATE using the alias name GleAdjDate.
     * @return the GLE_ADJ_DATE
     */
    public Timestamp getGleAdjDate() {
        return (Timestamp) getAttributeInternal(GLEADJDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for GLE_ADJ_DATE using the alias name GleAdjDate.
     * @param value value to set the GLE_ADJ_DATE
     */
    public void setGleAdjDate(Timestamp value) {
        setAttributeInternal(GLEADJDATE, value);
    }

    /**
     * Gets the attribute value for GLE_ADJ_TNS_CHILD_ID using the alias name GleAdjTnsChildId.
     * @return the GLE_ADJ_TNS_CHILD_ID
     */
    public Long getGleAdjTnsChildId() {
        return (Long) getAttributeInternal(GLEADJTNSCHILDID);
    }

    /**
     * Sets <code>value</code> as attribute value for GLE_ADJ_TNS_CHILD_ID using the alias name GleAdjTnsChildId.
     * @param value value to set the GLE_ADJ_TNS_CHILD_ID
     */
    public void setGleAdjTnsChildId(Long value) {
        setAttributeInternal(GLEADJTNSCHILDID, value);
    }

    /**
     * Gets the attribute value for GLE_ADJ_TNS_ID using the alias name GleAdjTnsId.
     * @return the GLE_ADJ_TNS_ID
     */
    public Long getGleAdjTnsId() {
        return (Long) getAttributeInternal(GLEADJTNSID);
    }

    /**
     * Sets <code>value</code> as attribute value for GLE_ADJ_TNS_ID using the alias name GleAdjTnsId.
     * @param value value to set the GLE_ADJ_TNS_ID
     */
    public void setGleAdjTnsId(Long value) {
        setAttributeInternal(GLEADJTNSID, value);
    }

    /**
     * Gets the attribute value for GLE_AVGRATE using the alias name GleAvgrate.
     * @return the GLE_AVGRATE
     */
    public BigDecimal getGleAvgrate() {
        return (BigDecimal) getAttributeInternal(GLEAVGRATE);
    }

    /**
     * Sets <code>value</code> as attribute value for GLE_AVGRATE using the alias name GleAvgrate.
     * @param value value to set the GLE_AVGRATE
     */
    public void setGleAvgrate(BigDecimal value) {
        setAttributeInternal(GLEAVGRATE, value);
    }

    /**
     * Gets the attribute value for GLE_BALANCE using the alias name GleBalance.
     * @return the GLE_BALANCE
     */
    public BigDecimal getGleBalance() {
        return (BigDecimal) getAttributeInternal(GLEBALANCE);
    }

    /**
     * Sets <code>value</code> as attribute value for GLE_BALANCE using the alias name GleBalance.
     * @param value value to set the GLE_BALANCE
     */
    public void setGleBalance(BigDecimal value) {
        setAttributeInternal(GLEBALANCE, value);
    }

    /**
     * Gets the attribute value for GLE_BANK_NAME using the alias name GleBankName.
     * @return the GLE_BANK_NAME
     */
    public String getGleBankName() {
        return (String) getAttributeInternal(GLEBANKNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for GLE_BANK_NAME using the alias name GleBankName.
     * @param value value to set the GLE_BANK_NAME
     */
    public void setGleBankName(String value) {
        setAttributeInternal(GLEBANKNAME, value);
    }

    /**
     * Gets the attribute value for GLE_BANK_NAME_ID using the alias name GleBankNameId.
     * @return the GLE_BANK_NAME_ID
     */
    public Long getGleBankNameId() {
        return (Long) getAttributeInternal(GLEBANKNAMEID);
    }

    /**
     * Sets <code>value</code> as attribute value for GLE_BANK_NAME_ID using the alias name GleBankNameId.
     * @param value value to set the GLE_BANK_NAME_ID
     */
    public void setGleBankNameId(Long value) {
        setAttributeInternal(GLEBANKNAMEID, value);
    }

    /**
     * Gets the attribute value for GLE_BANK_TNS_TYP_ID_FK using the alias name GleBankTnsTypIdFk.
     * @return the GLE_BANK_TNS_TYP_ID_FK
     */
    public Long getGleBankTnsTypIdFk() {
        return (Long) getAttributeInternal(GLEBANKTNSTYPIDFK);
    }

    /**
     * Sets <code>value</code> as attribute value for GLE_BANK_TNS_TYP_ID_FK using the alias name GleBankTnsTypIdFk.
     * @param value value to set the GLE_BANK_TNS_TYP_ID_FK
     */
    public void setGleBankTnsTypIdFk(Long value) {
        setAttributeInternal(GLEBANKTNSTYPIDFK, value);
    }

    /**
     * Gets the attribute value for GLE_BR_CODE using the alias name GleBrCode.
     * @return the GLE_BR_CODE
     */
    public String getGleBrCode() {
        return (String) getAttributeInternal(GLEBRCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for GLE_BR_CODE using the alias name GleBrCode.
     * @param value value to set the GLE_BR_CODE
     */
    public void setGleBrCode(String value) {
        setAttributeInternal(GLEBRCODE, value);
    }

    /**
     * Gets the attribute value for GLE_CGS_FLAG using the alias name GleCgsFlag.
     * @return the GLE_CGS_FLAG
     */
    public Long getGleCgsFlag() {
        return (Long) getAttributeInternal(GLECGSFLAG);
    }

    /**
     * Sets <code>value</code> as attribute value for GLE_CGS_FLAG using the alias name GleCgsFlag.
     * @param value value to set the GLE_CGS_FLAG
     */
    public void setGleCgsFlag(Long value) {
        setAttributeInternal(GLECGSFLAG, value);
    }

    /**
     * Gets the attribute value for GLE_CGS_RATE using the alias name GleCgsRate.
     * @return the GLE_CGS_RATE
     */
    public BigDecimal getGleCgsRate() {
        return (BigDecimal) getAttributeInternal(GLECGSRATE);
    }

    /**
     * Sets <code>value</code> as attribute value for GLE_CGS_RATE using the alias name GleCgsRate.
     * @param value value to set the GLE_CGS_RATE
     */
    public void setGleCgsRate(BigDecimal value) {
        setAttributeInternal(GLECGSRATE, value);
    }

    /**
     * Gets the attribute value for GLE_COA_ACT_NUMBER using the alias name GleCoaActNumber.
     * @return the GLE_COA_ACT_NUMBER
     */
    public Long getGleCoaActNumber() {
        return (Long) getAttributeInternal(GLECOAACTNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for GLE_COA_ACT_NUMBER using the alias name GleCoaActNumber.
     * @param value value to set the GLE_COA_ACT_NUMBER
     */
    public void setGleCoaActNumber(Long value) {
        setAttributeInternal(GLECOAACTNUMBER, value);
    }

    /**
     * Gets the attribute value for GLE_COA_EXEMPT_SALES_PURCHASE using the alias name GleCoaExemptSalesPurchase.
     * @return the GLE_COA_EXEMPT_SALES_PURCHASE
     */
    public Long getGleCoaExemptSalesPurchase() {
        return (Long) getAttributeInternal(GLECOAEXEMPTSALESPURCHASE);
    }

    /**
     * Sets <code>value</code> as attribute value for GLE_COA_EXEMPT_SALES_PURCHASE using the alias name GleCoaExemptSalesPurchase.
     * @param value value to set the GLE_COA_EXEMPT_SALES_PURCHASE
     */
    public void setGleCoaExemptSalesPurchase(Long value) {
        setAttributeInternal(GLECOAEXEMPTSALESPURCHASE, value);
    }

    /**
     * Gets the attribute value for GLE_CREDIT using the alias name GleCredit.
     * @return the GLE_CREDIT
     */
    public BigDecimal getGleCredit() {
        return (BigDecimal) getAttributeInternal(GLECREDIT);
    }

    /**
     * Sets <code>value</code> as attribute value for GLE_CREDIT using the alias name GleCredit.
     * @param value value to set the GLE_CREDIT
     */
    public void setGleCredit(BigDecimal value) {
        setAttributeInternal(GLECREDIT, value);
    }

    /**
     * Gets the attribute value for GLE_CREDIT_QTY using the alias name GleCreditQty.
     * @return the GLE_CREDIT_QTY
     */
    public BigDecimal getGleCreditQty() {
        return (BigDecimal) getAttributeInternal(GLECREDITQTY);
    }

    /**
     * Sets <code>value</code> as attribute value for GLE_CREDIT_QTY using the alias name GleCreditQty.
     * @param value value to set the GLE_CREDIT_QTY
     */
    public void setGleCreditQty(BigDecimal value) {
        setAttributeInternal(GLECREDITQTY, value);
    }

    /**
     * Gets the attribute value for GLE_DATE using the alias name GleDate.
     * @return the GLE_DATE
     */
    public Timestamp getGleDate() {
        return (Timestamp) getAttributeInternal(GLEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for GLE_DATE using the alias name GleDate.
     * @param value value to set the GLE_DATE
     */
    public void setGleDate(Timestamp value) {
        setAttributeInternal(GLEDATE, value);
    }

    /**
     * Gets the attribute value for GLE_DEBIT using the alias name GleDebit.
     * @return the GLE_DEBIT
     */
    public BigDecimal getGleDebit() {
        return (BigDecimal) getAttributeInternal(GLEDEBIT);
    }

    /**
     * Sets <code>value</code> as attribute value for GLE_DEBIT using the alias name GleDebit.
     * @param value value to set the GLE_DEBIT
     */
    public void setGleDebit(BigDecimal value) {
        setAttributeInternal(GLEDEBIT, value);
    }

    /**
     * Gets the attribute value for GLE_DEBIT_BAL using the alias name GleDebitBal.
     * @return the GLE_DEBIT_BAL
     */
    public BigDecimal getGleDebitBal() {
        return (BigDecimal) getAttributeInternal(GLEDEBITBAL);
    }

    /**
     * Sets <code>value</code> as attribute value for GLE_DEBIT_BAL using the alias name GleDebitBal.
     * @param value value to set the GLE_DEBIT_BAL
     */
    public void setGleDebitBal(BigDecimal value) {
        setAttributeInternal(GLEDEBITBAL, value);
    }

    /**
     * Gets the attribute value for GLE_DEBIT_QTY using the alias name GleDebitQty.
     * @return the GLE_DEBIT_QTY
     */
    public BigDecimal getGleDebitQty() {
        return (BigDecimal) getAttributeInternal(GLEDEBITQTY);
    }

    /**
     * Sets <code>value</code> as attribute value for GLE_DEBIT_QTY using the alias name GleDebitQty.
     * @param value value to set the GLE_DEBIT_QTY
     */
    public void setGleDebitQty(BigDecimal value) {
        setAttributeInternal(GLEDEBITQTY, value);
    }

    /**
     * Gets the attribute value for GLE_DETAILS using the alias name GleDetails.
     * @return the GLE_DETAILS
     */
    public String getGleDetails() {
        return (String) getAttributeInternal(GLEDETAILS);
    }

    /**
     * Sets <code>value</code> as attribute value for GLE_DETAILS using the alias name GleDetails.
     * @param value value to set the GLE_DETAILS
     */
    public void setGleDetails(String value) {
        setAttributeInternal(GLEDETAILS, value);
    }

    /**
     * Gets the attribute value for GLE_ETC using the alias name GleEtc.
     * @return the GLE_ETC
     */
    public String getGleEtc() {
        return (String) getAttributeInternal(GLEETC);
    }

    /**
     * Sets <code>value</code> as attribute value for GLE_ETC using the alias name GleEtc.
     * @param value value to set the GLE_ETC
     */
    public void setGleEtc(String value) {
        setAttributeInternal(GLEETC, value);
    }

    /**
     * Gets the attribute value for GLE_ID using the alias name GleId.
     * @return the GLE_ID
     */
    public DBSequence getGleId() {
        return (DBSequence) getAttributeInternal(GLEID);
    }

    /**
     * Sets <code>value</code> as attribute value for GLE_ID using the alias name GleId.
     * @param value value to set the GLE_ID
     */
    public void setGleId(DBSequence value) {
        setAttributeInternal(GLEID, value);
    }

    /**
     * Gets the attribute value for GLE_INFO using the alias name GleInfo.
     * @return the GLE_INFO
     */
    public String getGleInfo() {
        return (String) getAttributeInternal(GLEINFO);
    }

    /**
     * Sets <code>value</code> as attribute value for GLE_INFO using the alias name GleInfo.
     * @param value value to set the GLE_INFO
     */
    public void setGleInfo(String value) {
        setAttributeInternal(GLEINFO, value);
    }

    /**
     * Gets the attribute value for GLE_OIL_D_ID using the alias name GleOilDId.
     * @return the GLE_OIL_D_ID
     */
    public Long getGleOilDId() {
        return (Long) getAttributeInternal(GLEOILDID);
    }

    /**
     * Sets <code>value</code> as attribute value for GLE_OIL_D_ID using the alias name GleOilDId.
     * @param value value to set the GLE_OIL_D_ID
     */
    public void setGleOilDId(Long value) {
        setAttributeInternal(GLEOILDID, value);
    }

    /**
     * Gets the attribute value for GLE_OIL_T_ID using the alias name GleOilTId.
     * @return the GLE_OIL_T_ID
     */
    public Long getGleOilTId() {
        return (Long) getAttributeInternal(GLEOILTID);
    }

    /**
     * Sets <code>value</code> as attribute value for GLE_OIL_T_ID using the alias name GleOilTId.
     * @param value value to set the GLE_OIL_T_ID
     */
    public void setGleOilTId(Long value) {
        setAttributeInternal(GLEOILTID, value);
    }

    /**
     * Gets the attribute value for GLE_OILD_LOAD_DATE using the alias name GleOildLoadDate.
     * @return the GLE_OILD_LOAD_DATE
     */
    public Timestamp getGleOildLoadDate() {
        return (Timestamp) getAttributeInternal(GLEOILDLOADDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for GLE_OILD_LOAD_DATE using the alias name GleOildLoadDate.
     * @param value value to set the GLE_OILD_LOAD_DATE
     */
    public void setGleOildLoadDate(Timestamp value) {
        setAttributeInternal(GLEOILDLOADDATE, value);
    }

    /**
     * Gets the attribute value for GLE_OILD_LOAD_ID using the alias name GleOildLoadId.
     * @return the GLE_OILD_LOAD_ID
     */
    public Long getGleOildLoadId() {
        return (Long) getAttributeInternal(GLEOILDLOADID);
    }

    /**
     * Sets <code>value</code> as attribute value for GLE_OILD_LOAD_ID using the alias name GleOildLoadId.
     * @param value value to set the GLE_OILD_LOAD_ID
     */
    public void setGleOildLoadId(Long value) {
        setAttributeInternal(GLEOILDLOADID, value);
    }

    /**
     * Gets the attribute value for GLE_OLDW using the alias name GleOldw.
     * @return the GLE_OLDW
     */
    public Integer getGleOldw() {
        return (Integer) getAttributeInternal(GLEOLDW);
    }

    /**
     * Sets <code>value</code> as attribute value for GLE_OLDW using the alias name GleOldw.
     * @param value value to set the GLE_OLDW
     */
    public void setGleOldw(Integer value) {
        setAttributeInternal(GLEOLDW, value);
    }

    /**
     * Gets the attribute value for GLE_PL_FLAG using the alias name GlePlFlag.
     * @return the GLE_PL_FLAG
     */
    public Long getGlePlFlag() {
        return (Long) getAttributeInternal(GLEPLFLAG);
    }

    /**
     * Sets <code>value</code> as attribute value for GLE_PL_FLAG using the alias name GlePlFlag.
     * @param value value to set the GLE_PL_FLAG
     */
    public void setGlePlFlag(Long value) {
        setAttributeInternal(GLEPLFLAG, value);
    }

    /**
     * Gets the attribute value for GLE_QTY using the alias name GleQty.
     * @return the GLE_QTY
     */
    public BigDecimal getGleQty() {
        return (BigDecimal) getAttributeInternal(GLEQTY);
    }

    /**
     * Sets <code>value</code> as attribute value for GLE_QTY using the alias name GleQty.
     * @param value value to set the GLE_QTY
     */
    public void setGleQty(BigDecimal value) {
        setAttributeInternal(GLEQTY, value);
    }

    /**
     * Gets the attribute value for GLE_QTY_BAL using the alias name GleQtyBal.
     * @return the GLE_QTY_BAL
     */
    public BigDecimal getGleQtyBal() {
        return (BigDecimal) getAttributeInternal(GLEQTYBAL);
    }

    /**
     * Sets <code>value</code> as attribute value for GLE_QTY_BAL using the alias name GleQtyBal.
     * @param value value to set the GLE_QTY_BAL
     */
    public void setGleQtyBal(BigDecimal value) {
        setAttributeInternal(GLEQTYBAL, value);
    }

    /**
     * Gets the attribute value for GLE_QTY_BALANCE using the alias name GleQtyBalance.
     * @return the GLE_QTY_BALANCE
     */
    public BigDecimal getGleQtyBalance() {
        return (BigDecimal) getAttributeInternal(GLEQTYBALANCE);
    }

    /**
     * Sets <code>value</code> as attribute value for GLE_QTY_BALANCE using the alias name GleQtyBalance.
     * @param value value to set the GLE_QTY_BALANCE
     */
    public void setGleQtyBalance(BigDecimal value) {
        setAttributeInternal(GLEQTYBALANCE, value);
    }

    /**
     * Gets the attribute value for GLE_RATE using the alias name GleRate.
     * @return the GLE_RATE
     */
    public BigDecimal getGleRate() {
        return (BigDecimal) getAttributeInternal(GLERATE);
    }

    /**
     * Sets <code>value</code> as attribute value for GLE_RATE using the alias name GleRate.
     * @param value value to set the GLE_RATE
     */
    public void setGleRate(BigDecimal value) {
        setAttributeInternal(GLERATE, value);
    }

    /**
     * Gets the attribute value for GLE_S_DATE using the alias name GleSDate.
     * @return the GLE_S_DATE
     */
    public Timestamp getGleSDate() {
        return (Timestamp) getAttributeInternal(GLESDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for GLE_S_DATE using the alias name GleSDate.
     * @param value value to set the GLE_S_DATE
     */
    public void setGleSDate(Timestamp value) {
        setAttributeInternal(GLESDATE, value);
    }

    /**
     * Gets the attribute value for GLE_SLIP_DATE using the alias name GleSlipDate.
     * @return the GLE_SLIP_DATE
     */
    public Timestamp getGleSlipDate() {
        return (Timestamp) getAttributeInternal(GLESLIPDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for GLE_SLIP_DATE using the alias name GleSlipDate.
     * @param value value to set the GLE_SLIP_DATE
     */
    public void setGleSlipDate(Timestamp value) {
        setAttributeInternal(GLESLIPDATE, value);
    }

    /**
     * Gets the attribute value for GLE_SLIP_NO using the alias name GleSlipNo.
     * @return the GLE_SLIP_NO
     */
    public String getGleSlipNo() {
        return (String) getAttributeInternal(GLESLIPNO);
    }

    /**
     * Sets <code>value</code> as attribute value for GLE_SLIP_NO using the alias name GleSlipNo.
     * @param value value to set the GLE_SLIP_NO
     */
    public void setGleSlipNo(String value) {
        setAttributeInternal(GLESLIPNO, value);
    }

    /**
     * Gets the attribute value for "Synchronize:Fix_SQL" using the alias name GleSlipUseDate.
     * @return the "Synchronize:Fix_SQL"
     */
    public Timestamp getGleSlipUseDate() {
        return (Timestamp) getAttributeInternal(GLESLIPUSEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for "Synchronize:Fix_SQL" using the alias name GleSlipUseDate.
     * @param value value to set the "Synchronize:Fix_SQL"
     */
    public void setGleSlipUseDate(Timestamp value) {
        setAttributeInternal(GLESLIPUSEDATE, value);
    }

    /**
     * Gets the attribute value for GLE_ST_ID using the alias name GleStId.
     * @return the GLE_ST_ID
     */
    public Long getGleStId() {
        return (Long) getAttributeInternal(GLESTID);
    }

    /**
     * Sets <code>value</code> as attribute value for GLE_ST_ID using the alias name GleStId.
     * @param value value to set the GLE_ST_ID
     */
    public void setGleStId(Long value) {
        setAttributeInternal(GLESTID, value);
    }

    /**
     * Gets the attribute value for "Synchronize:Fix_SQL" using the alias name GleTnsBankId.
     * @return the "Synchronize:Fix_SQL"
     */
    public Long getGleTnsBankId() {
        return (Long) getAttributeInternal(GLETNSBANKID);
    }

    /**
     * Sets <code>value</code> as attribute value for "Synchronize:Fix_SQL" using the alias name GleTnsBankId.
     * @param value value to set the "Synchronize:Fix_SQL"
     */
    public void setGleTnsBankId(Long value) {
        setAttributeInternal(GLETNSBANKID, value);
    }

    /**
     * Gets the attribute value for GLE_TNS_CHILD_ID_FK using the alias name GleTnsChildIdFk.
     * @return the GLE_TNS_CHILD_ID_FK
     */
    public Long getGleTnsChildIdFk() {
        return (Long) getAttributeInternal(GLETNSCHILDIDFK);
    }

    /**
     * Sets <code>value</code> as attribute value for GLE_TNS_CHILD_ID_FK using the alias name GleTnsChildIdFk.
     * @param value value to set the GLE_TNS_CHILD_ID_FK
     */
    public void setGleTnsChildIdFk(Long value) {
        setAttributeInternal(GLETNSCHILDIDFK, value);
    }

    /**
     * Gets the attribute value for GLE_TNS_ID using the alias name GleTnsId.
     * @return the GLE_TNS_ID
     */
    public Long getGleTnsId() {
        return (Long) getAttributeInternal(GLETNSID);
    }

    /**
     * Sets <code>value</code> as attribute value for GLE_TNS_ID using the alias name GleTnsId.
     * @param value value to set the GLE_TNS_ID
     */
    public void setGleTnsId(Long value) {
        setAttributeInternal(GLETNSID, value);
    }

    /**
     * Gets the attribute value for GLE_TNS_VIEW_ID using the alias name GleTnsViewId.
     * @return the GLE_TNS_VIEW_ID
     */
    public Long getGleTnsViewId() {
        return (Long) getAttributeInternal(GLETNSVIEWID);
    }

    /**
     * Sets <code>value</code> as attribute value for GLE_TNS_VIEW_ID using the alias name GleTnsViewId.
     * @param value value to set the GLE_TNS_VIEW_ID
     */
    public void setGleTnsViewId(Long value) {
        setAttributeInternal(GLETNSVIEWID, value);
    }

    /**
     * Gets the attribute value for BANK_NAME using the alias name BankName1.
     * @return the BANK_NAME
     */
    public String getBankName1() {
        return (String) getAttributeInternal(BANKNAME1);
    }

    /**
     * Sets <code>value</code> as attribute value for BANK_NAME using the alias name BankName1.
     * @param value value to set the BANK_NAME
     */
    public void setBankName1(String value) {
        setAttributeInternal(BANKNAME1, value);
    }

    /**
     * Gets the attribute value for BANK_NAME_ID using the alias name BankNameId.
     * @return the BANK_NAME_ID
     */
    public DBSequence getBankNameId() {
        return (DBSequence) getAttributeInternal(BANKNAMEID);
    }

    /**
     * Sets <code>value</code> as attribute value for BANK_NAME_ID using the alias name BankNameId.
     * @param value value to set the BANK_NAME_ID
     */
    public void setBankNameId(DBSequence value) {
        setAttributeInternal(BANKNAMEID, value);
    }

    /**
     * Gets the attribute value for BANK_TNS_TYPE_NAME using the alias name BankTnsTypeName.
     * @return the BANK_TNS_TYPE_NAME
     */
    public String getBankTnsTypeName() {
        return (String) getAttributeInternal(BANKTNSTYPENAME);
    }

    /**
     * Sets <code>value</code> as attribute value for BANK_TNS_TYPE_NAME using the alias name BankTnsTypeName.
     * @param value value to set the BANK_TNS_TYPE_NAME
     */
    public void setBankTnsTypeName(String value) {
        setAttributeInternal(BANKTNSTYPENAME, value);
    }

    /**
     * Gets the attribute value for BANK_TNS_TYPE_ID using the alias name BankTnsTypeId.
     * @return the BANK_TNS_TYPE_ID
     */
    public DBSequence getBankTnsTypeId() {
        return (DBSequence) getAttributeInternal(BANKTNSTYPEID);
    }

    /**
     * Sets <code>value</code> as attribute value for BANK_TNS_TYPE_ID using the alias name BankTnsTypeId.
     * @param value value to set the BANK_TNS_TYPE_ID
     */
    public void setBankTnsTypeId(DBSequence value) {
        setAttributeInternal(BANKTNSTYPEID, value);
    }

    /**
     * Gets the attribute value for OILD_SHORTNAME using the alias name OildShortname.
     * @return the OILD_SHORTNAME
     */
    public String getOildShortname() {
        return (String) getAttributeInternal(OILDSHORTNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for OILD_SHORTNAME using the alias name OildShortname.
     * @param value value to set the OILD_SHORTNAME
     */
    public void setOildShortname(String value) {
        setAttributeInternal(OILDSHORTNAME, value);
    }

    /**
     * Gets the attribute value for OILD_ID using the alias name OildId.
     * @return the OILD_ID
     */
    public DBSequence getOildId() {
        return (DBSequence) getAttributeInternal(OILDID);
    }

    /**
     * Sets <code>value</code> as attribute value for OILD_ID using the alias name OildId.
     * @param value value to set the OILD_ID
     */
    public void setOildId(DBSequence value) {
        setAttributeInternal(OILDID, value);
    }

    /**
     * Gets the attribute value for OILT_REGISTRATION# using the alias name OiltRegistration.
     * @return the OILT_REGISTRATION#
     */
    public String getOiltRegistration() {
        return (String) getAttributeInternal(OILTREGISTRATION);
    }

    /**
     * Sets <code>value</code> as attribute value for OILT_REGISTRATION# using the alias name OiltRegistration.
     * @param value value to set the OILT_REGISTRATION#
     */
    public void setOiltRegistration(String value) {
        setAttributeInternal(OILTREGISTRATION, value);
    }

    /**
     * Gets the attribute value for OILT_ID using the alias name OiltId.
     * @return the OILT_ID
     */
    public DBSequence getOiltId() {
        return (DBSequence) getAttributeInternal(OILTID);
    }

    /**
     * Sets <code>value</code> as attribute value for OILT_ID using the alias name OiltId.
     * @param value value to set the OILT_ID
     */
    public void setOiltId(DBSequence value) {
        setAttributeInternal(OILTID, value);
    }

    /**
     * Gets the attribute value for OILD_SHORTNAME using the alias name OildShortname1.
     * @return the OILD_SHORTNAME
     */
    public String getOildShortname1() {
        return (String) getAttributeInternal(OILDSHORTNAME1);
    }

    /**
     * Sets <code>value</code> as attribute value for OILD_SHORTNAME using the alias name OildShortname1.
     * @param value value to set the OILD_SHORTNAME
     */
    public void setOildShortname1(String value) {
        setAttributeInternal(OILDSHORTNAME1, value);
    }

    /**
     * Gets the attribute value for OILD_ID using the alias name OildId1.
     * @return the OILD_ID
     */
    public DBSequence getOildId1() {
        return (DBSequence) getAttributeInternal(OILDID1);
    }

    /**
     * Sets <code>value</code> as attribute value for OILD_ID using the alias name OildId1.
     * @param value value to set the OILD_ID
     */
    public void setOildId1(DBSequence value) {
        setAttributeInternal(OILDID1, value);
    }

    /**
     * Gets the attribute value for COA_NAME using the alias name CoaName.
     * @return the COA_NAME
     */
    public String getCoaName() {
        return (String) getAttributeInternal(COANAME);
    }

    /**
     * Sets <code>value</code> as attribute value for COA_NAME using the alias name CoaName.
     * @param value value to set the COA_NAME
     */
    public void setCoaName(String value) {
        setAttributeInternal(COANAME, value);
    }

    /**
     * Gets the attribute value for COA_ACT_NUMBER using the alias name CoaActNumber.
     * @return the COA_ACT_NUMBER
     */
    public Long getCoaActNumber() {
        return (Long) getAttributeInternal(COAACTNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for COA_ACT_NUMBER using the alias name CoaActNumber.
     * @param value value to set the COA_ACT_NUMBER
     */
    public void setCoaActNumber(Long value) {
        setAttributeInternal(COAACTNUMBER, value);
    }

    /**
     * Gets the attribute value for COA_BALANCE using the alias name CoaBalance.
     * @return the COA_BALANCE
     */
    public BigDecimal getCoaBalance() {
        return (BigDecimal) getAttributeInternal(COABALANCE);
    }

    /**
     * Gets the attribute value for COA_NAME using the alias name CoaName1.
     * @return the COA_NAME
     */
    public String getCoaName1() {
        return (String) getAttributeInternal(COANAME1);
    }

    /**
     * Sets <code>value</code> as attribute value for COA_NAME using the alias name CoaName1.
     * @param value value to set the COA_NAME
     */
    public void setCoaName1(String value) {
        setAttributeInternal(COANAME1, value);
    }

    /**
     * Gets the attribute value for COA_ACT_NUMBER using the alias name CoaActNumber1.
     * @return the COA_ACT_NUMBER
     */
    public Long getCoaActNumber1() {
        return (Long) getAttributeInternal(COAACTNUMBER1);
    }

    /**
     * Sets <code>value</code> as attribute value for COA_ACT_NUMBER using the alias name CoaActNumber1.
     * @param value value to set the COA_ACT_NUMBER
     */
    public void setCoaActNumber1(Long value) {
        setAttributeInternal(COAACTNUMBER1, value);
    }

    /**
     * Gets the attribute value for VEHICLE_ID_FK using the alias name VehicleIdFk.
     * @return the VEHICLE_ID_FK
     */
    public Long getVehicleIdFk() {
        return (Long) getAttributeInternal(VEHICLEIDFK);
    }

    /**
     * Sets <code>value</code> as attribute value for VEHICLE_ID_FK using the alias name VehicleIdFk.
     * @param value value to set the VEHICLE_ID_FK
     */
    public void setVehicleIdFk(Long value) {
        setAttributeInternal(VEHICLEIDFK, value);
    }

    /**
     * Gets the attribute value for VEHICLE_REG_NO using the alias name VehicleRegNo.
     * @return the VEHICLE_REG_NO
     */
    public String getVehicleRegNo() {
        return (String) getAttributeInternal(VEHICLEREGNO);
    }

    /**
     * Sets <code>value</code> as attribute value for VEHICLE_REG_NO using the alias name VehicleRegNo.
     * @param value value to set the VEHICLE_REG_NO
     */
    public void setVehicleRegNo(String value) {
        setAttributeInternal(VEHICLEREGNO, value);
    }

    /**
     * Gets the attribute value for VEHICLE_ID using the alias name VehicleId.
     * @return the VEHICLE_ID
     */
    public DBSequence getVehicleId() {
        return (DBSequence) getAttributeInternal(VEHICLEID);
    }

    /**
     * Sets <code>value</code> as attribute value for VEHICLE_ID using the alias name VehicleId.
     * @param value value to set the VEHICLE_ID
     */
    public void setVehicleId(DBSequence value) {
        setAttributeInternal(VEHICLEID, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> BankNameView1.
     */
    public RowSet getBankNameView1() {
        return (RowSet) getAttributeInternal(BANKNAMEVIEW1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> OIL_DEPO_WITH_NA_VIEW1.
     */
    public RowSet getOIL_DEPO_WITH_NA_VIEW1() {
        return (RowSet) getAttributeInternal(OIL_DEPO_WITH_NA_VIEW1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> OilTankerAllView1.
     */
    public RowSet getOilTankerAllView1() {
        return (RowSet) getAttributeInternal(OILTANKERALLVIEW1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> OIL_DEPO_WITH_NA_VIEW2.
     */
    public RowSet getOIL_DEPO_WITH_NA_VIEW2() {
        return (RowSet) getAttributeInternal(OIL_DEPO_WITH_NA_VIEW2);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AppModule_CoaAllWithstatedCapital1_1.
     */
    public RowSet getAppModule_CoaAllWithstatedCapital1_1() {
        return (RowSet) getAttributeInternal(APPMODULE_COAALLWITHSTATEDCAPITAL1_1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> CoaAllWithstatedCapital1.
     */
    public RowSet getCoaAllWithstatedCapital1() {
        return (RowSet) getAttributeInternal(COAALLWITHSTATEDCAPITAL1);
    }
}

