package model;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jan 28 01:41:36 PKT 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class infoDMLOpeImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public infoDMLOpeImpl() {
    }
}

