package model;

import java.math.BigDecimal;

import java.math.MathContext;
import java.math.RoundingMode;

import java.sql.Timestamp;

import oracle.jbo.ApplicationModule;
import oracle.jbo.RowSet;
import oracle.jbo.domain.DBSequence;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Jan 31 03:26:04 PKT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SALE_RETAILRowImpl extends ViewRowImpl {


    public static final int ENTITY_TRANSACTION = 0;
    public static final int ENTITY_CHARTOFACCOUNTS = 1;
    public static final int ENTITY_CHARTOFACCOUNTS1 = 2;
    public static final int ENTITY_VEHICLE1 = 3;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        TnsAmount,
        TnsInfo,
        TnsFormatAmount,
        TnsDate,
        TnsRate,
        TnsQty,
        TnsSlipDate,
        TnsSlipNo,
        TnsSpellAmount,
        TnsTnsTypeIdFk,
        TnsTnsviewId,
        TnsId,
        CoaName,
        CoaActNumber,
        CoaBalance,
        CoaName1,
        CoaActNumber1,
        CoaBalance1,
        TnsCoaCactNumber,
        TnsCoaDactNumber,
        VehicleRegNo,
        VehicleId,
        VehicleIdFk,
        TnsSDate,
        TnsFreightfactor,
        COA_PARTY_CUSTOMER_CASH1,
        COAPRoductRevenue1,
        Vehicle1View1;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int TNSAMOUNT = AttributesEnum.TnsAmount.index();
    public static final int TNSINFO = AttributesEnum.TnsInfo.index();
    public static final int TNSFORMATAMOUNT = AttributesEnum.TnsFormatAmount.index();
    public static final int TNSDATE = AttributesEnum.TnsDate.index();
    public static final int TNSRATE = AttributesEnum.TnsRate.index();
    public static final int TNSQTY = AttributesEnum.TnsQty.index();
    public static final int TNSSLIPDATE = AttributesEnum.TnsSlipDate.index();
    public static final int TNSSLIPNO = AttributesEnum.TnsSlipNo.index();
    public static final int TNSSPELLAMOUNT = AttributesEnum.TnsSpellAmount.index();
    public static final int TNSTNSTYPEIDFK = AttributesEnum.TnsTnsTypeIdFk.index();
    public static final int TNSTNSVIEWID = AttributesEnum.TnsTnsviewId.index();
    public static final int TNSID = AttributesEnum.TnsId.index();
    public static final int COANAME = AttributesEnum.CoaName.index();
    public static final int COAACTNUMBER = AttributesEnum.CoaActNumber.index();
    public static final int COABALANCE = AttributesEnum.CoaBalance.index();
    public static final int COANAME1 = AttributesEnum.CoaName1.index();
    public static final int COAACTNUMBER1 = AttributesEnum.CoaActNumber1.index();
    public static final int COABALANCE1 = AttributesEnum.CoaBalance1.index();
    public static final int TNSCOACACTNUMBER = AttributesEnum.TnsCoaCactNumber.index();
    public static final int TNSCOADACTNUMBER = AttributesEnum.TnsCoaDactNumber.index();
    public static final int VEHICLEREGNO = AttributesEnum.VehicleRegNo.index();
    public static final int VEHICLEID = AttributesEnum.VehicleId.index();
    public static final int VEHICLEIDFK = AttributesEnum.VehicleIdFk.index();
    public static final int TNSSDATE = AttributesEnum.TnsSDate.index();
    public static final int TNSFREIGHTFACTOR = AttributesEnum.TnsFreightfactor.index();
    public static final int COA_PARTY_CUSTOMER_CASH1 = AttributesEnum.COA_PARTY_CUSTOMER_CASH1.index();
    public static final int COAPRODUCTREVENUE1 = AttributesEnum.COAPRoductRevenue1.index();
    public static final int VEHICLE1VIEW1 = AttributesEnum.Vehicle1View1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public SALE_RETAILRowImpl() {
    }

    /**
     * Gets Transaction entity object.
     * @return the Transaction
     */
    public TransactionImpl getTransaction() {
        return (TransactionImpl) getEntity(ENTITY_TRANSACTION);
    }

    /**
     * Gets ChartOfAccounts entity object.
     * @return the ChartOfAccounts
     */
    public EntityImpl getChartOfAccounts() {
        return (EntityImpl) getEntity(ENTITY_CHARTOFACCOUNTS);
    }

    /**
     * Gets ChartOfAccounts1 entity object.
     * @return the ChartOfAccounts1
     */
    public EntityImpl getChartOfAccounts1() {
        return (EntityImpl) getEntity(ENTITY_CHARTOFACCOUNTS1);
    }


    /**
     * Gets Vehicle1 entity object.
     * @return the Vehicle1
     */
    public EntityImpl getVehicle1() {
        return (EntityImpl) getEntity(ENTITY_VEHICLE1);
    }


    /**
     * Gets the attribute value for TNS_AMOUNT using the alias name TnsAmount.
     * @return the TNS_AMOUNT
     */
    public BigDecimal getTnsAmount() {
        return (BigDecimal) getAttributeInternal(TNSAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for TNS_AMOUNT using the alias name TnsAmount.
     * @param value value to set the TNS_AMOUNT
     */
    public void setTnsAmount(BigDecimal value) {
        setTnsFormatAmount( value);
           
           setAttributeInternal(TNSAMOUNT, value);
           String str=this.SpellAmount();
           this.setTnsSpellAmount(str);
        }


    /**
     * Gets the attribute value for TNS_INFO using the alias name TnsInfo.
     * @return the TNS_INFO
     */
    public String getTnsInfo() {
        return (String) getAttributeInternal(TNSINFO);
    }

    /**
     * Sets <code>value</code> as attribute value for TNS_INFO using the alias name TnsInfo.
     * @param value value to set the TNS_INFO
     */
    public void setTnsInfo(String value) {
        setAttributeInternal(TNSINFO, value);
    }

    /**
     * Gets the attribute value for TNS_FORMAT_AMOUNT using the alias name TnsFormatAmount.
     * @return the TNS_FORMAT_AMOUNT
     */
    public BigDecimal getTnsFormatAmount() {
        return (BigDecimal) getAttributeInternal(TNSAMOUNT);
      //  return (BigDecimal) getAttributeInternal(TNSFORMATAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for TNS_FORMAT_AMOUNT using the alias name TnsFormatAmount.
     * @param value value to set the TNS_FORMAT_AMOUNT
     */
    public void setTnsFormatAmount(BigDecimal value) {
        value=this.getTnsAmount();
        setAttributeInternal(TNSFORMATAMOUNT, value);
    }

    /**
     * Gets the attribute value for TNS_DATE using the alias name TnsDate.
     * @return the TNS_DATE
     */
    public Timestamp getTnsDate() {
        return (Timestamp) getAttributeInternal(TNSDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for TNS_DATE using the alias name TnsDate.
     * @param value value to set the TNS_DATE
     */
    public void setTnsDate(Timestamp value) {
        setAttributeInternal(TNSDATE, value);
        setAttributeInternal(TNSSLIPDATE, value);
    }

    /**
     * Gets the attribute value for TNS_RATE using the alias name TnsRate.
     * @return the TNS_RATE
     */
    public String getTnsRate() {
        return (String) getAttributeInternal(TNSRATE);
    }

    /**
     * Sets <code>value</code> as attribute value for TNS_RATE using the alias name TnsRate.
     * @param value value to set the TNS_RATE
     */
    public void setTnsRate(String value) {
        setAttributeInternal(TNSRATE, value);
       // this.calculateAmount();
        }

    /**
     * Gets the attribute value for TNS_QTY using the alias name TnsQty.
     * @return the TNS_QTY
     */
    public BigDecimal getTnsQty() {
        return (BigDecimal) getAttributeInternal(TNSQTY);
    }

    /**
     * Sets <code>value</code> as attribute value for TNS_QTY using the alias name TnsQty.
     * @param value value to set the TNS_QTY
     */
    public void setTnsQty(BigDecimal value) {
        setAttributeInternal(TNSQTY,value);
       
        Timestamp RDate= this.getTnsDate();
        Long productID =this.getTnsCoaCactNumber();
            productID=productID-5000000;
        String rate=this.execRetailRate(productID, RDate);
            setAttributeInternal(TNSRATE, rate);
        this.calculateAmount();
        
        }

    /**
     * Gets the attribute value for TNS_SLIP_DATE using the alias name TnsSlipDate.
     * @return the TNS_SLIP_DATE
     */
    public Timestamp getTnsSlipDate() {
        return (Timestamp) getAttributeInternal(TNSSLIPDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for TNS_SLIP_DATE using the alias name TnsSlipDate.
     * @param value value to set the TNS_SLIP_DATE
     */
    public void setTnsSlipDate(Timestamp value) {
        setAttributeInternal(TNSSLIPDATE, value);
    }

    /**
     * Gets the attribute value for TNS_SLIP_NO using the alias name TnsSlipNo.
     * @return the TNS_SLIP_NO
     */
    public String getTnsSlipNo() {
        return (String) getAttributeInternal(TNSSLIPNO);
    }

    /**
     * Sets <code>value</code> as attribute value for TNS_SLIP_NO using the alias name TnsSlipNo.
     * @param value value to set the TNS_SLIP_NO
     */
    public void setTnsSlipNo(String value) {
        setAttributeInternal(TNSSLIPNO, value);
    }

    /**
     * Gets the attribute value for TNS_SPELL_AMOUNT using the alias name TnsSpellAmount.
     * @return the TNS_SPELL_AMOUNT
     */
    public String getTnsSpellAmount() {
        return this.SpellAmount();       
      //  return (String) getAttributeInternal(TNSSPELLAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for TNS_SPELL_AMOUNT using the alias name TnsSpellAmount.
     * @param value value to set the TNS_SPELL_AMOUNT
     */
    public void setTnsSpellAmount(String value) {
        value=this.SpellAmount();
        setAttributeInternal(TNSSPELLAMOUNT, value);
    }

    /**
     * Gets the attribute value for TNS_TNS_TYPE_ID_FK using the alias name TnsTnsTypeIdFk.
     * @return the TNS_TNS_TYPE_ID_FK
     */
    public Long getTnsTnsTypeIdFk() {
        return (Long) getAttributeInternal(TNSTNSTYPEIDFK);
    }

    /**
     * Sets <code>value</code> as attribute value for TNS_TNS_TYPE_ID_FK using the alias name TnsTnsTypeIdFk.
     * @param value value to set the TNS_TNS_TYPE_ID_FK
     */
    public void setTnsTnsTypeIdFk(Long value) {
        setAttributeInternal(TNSTNSTYPEIDFK, value);
    }

    /**
     * Gets the attribute value for TNS_TNSVIEW_ID using the alias name TnsTnsviewId.
     * @return the TNS_TNSVIEW_ID
     */
    public Long getTnsTnsviewId() {
        return (Long) getAttributeInternal(TNSTNSVIEWID);
    }

    /**
     * Sets <code>value</code> as attribute value for TNS_TNSVIEW_ID using the alias name TnsTnsviewId.
     * @param value value to set the TNS_TNSVIEW_ID
     */
    public void setTnsTnsviewId(Long value) {
        setAttributeInternal(TNSTNSVIEWID, value);
    }

    /**
     * Gets the attribute value for TNS_ID using the alias name TnsId.
     * @return the TNS_ID
     */
    public DBSequence getTnsId() {
        return (DBSequence) getAttributeInternal(TNSID);
    }

    /**
     * Sets <code>value</code> as attribute value for TNS_ID using the alias name TnsId.
     * @param value value to set the TNS_ID
     */
    public void setTnsId(DBSequence value) {
        setAttributeInternal(TNSID, value);
    }

    /**
     * Gets the attribute value for COA_NAME using the alias name CoaName.
     * @return the COA_NAME
     */
    public String getCoaName() {
        return (String) getAttributeInternal(COANAME);
    }

    /**
     * Sets <code>value</code> as attribute value for COA_NAME using the alias name CoaName.
     * @param value value to set the COA_NAME
     */
    public void setCoaName(String value) {
        this.setTnsDate(this.getSelectedDateView());
        setAttributeInternal(COANAME, value);
    }

    /**
     * Gets the attribute value for COA_ACT_NUMBER using the alias name CoaActNumber.
     * @return the COA_ACT_NUMBER
     */
    public Long getCoaActNumber() {
        return (Long) getAttributeInternal(COAACTNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for COA_ACT_NUMBER using the alias name CoaActNumber.
     * @param value value to set the COA_ACT_NUMBER
     */
    public void setCoaActNumber(Long value) {
        setAttributeInternal(COAACTNUMBER, value);
    }

    /**
     * Gets the attribute value for COA_BALANCE using the alias name CoaBalance.
     * @return the COA_BALANCE
     */
    public BigDecimal getCoaBalance() {
        return (BigDecimal) getAttributeInternal(COABALANCE);
    }

    /**
     * Gets the attribute value for COA_NAME using the alias name CoaName1.
     * @return the COA_NAME
     */
    public String getCoaName1() {
        return (String) getAttributeInternal(COANAME1);
    }

    /**
     * Sets <code>value</code> as attribute value for COA_NAME using the alias name CoaName1.
     * @param value value to set the COA_NAME
     */
    public void setCoaName1(String value) {
        setAttributeInternal(COANAME1, value);
    }

    /**
     * Gets the attribute value for COA_ACT_NUMBER using the alias name CoaActNumber1.
     * @return the COA_ACT_NUMBER
     */
    public Long getCoaActNumber1() {
        return (Long) getAttributeInternal(COAACTNUMBER1);
    }

    /**
     * Sets <code>value</code> as attribute value for COA_ACT_NUMBER using the alias name CoaActNumber1.
     * @param value value to set the COA_ACT_NUMBER
     */
    public void setCoaActNumber1(Long value) {
        setAttributeInternal(COAACTNUMBER1, value);
    }

    /**
     * Gets the attribute value for COA_BALANCE using the alias name CoaBalance1.
     * @return the COA_BALANCE
     */
    public BigDecimal getCoaBalance1() {
        return (BigDecimal) getAttributeInternal(COABALANCE1);
    }

    /**
     * Gets the attribute value for TNS_COA_CACT_NUMBER using the alias name TnsCoaCactNumber.
     * @return the TNS_COA_CACT_NUMBER
     */
    public Long getTnsCoaCactNumber() {
        return (Long) getAttributeInternal(TNSCOACACTNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for TNS_COA_CACT_NUMBER using the alias name TnsCoaCactNumber.
     * @param value value to set the TNS_COA_CACT_NUMBER
     */
    public void setTnsCoaCactNumber(Long value) {
        setAttributeInternal(TNSCOACACTNUMBER, value);
    }

    /**
     * Gets the attribute value for TNS_COA_DACT_NUMBER using the alias name TnsCoaDactNumber.
     * @return the TNS_COA_DACT_NUMBER
     */
    public Long getTnsCoaDactNumber() {
        return (Long) getAttributeInternal(TNSCOADACTNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for TNS_COA_DACT_NUMBER using the alias name TnsCoaDactNumber.
     * @param value value to set the TNS_COA_DACT_NUMBER
     */
    public void setTnsCoaDactNumber(Long value) {
        setAttributeInternal(TNSCOADACTNUMBER, value);
    }

    /**
     * Gets the attribute value for VEHICLE_REG_NO using the alias name VehicleRegNo.
     * @return the VEHICLE_REG_NO
     */
    public String getVehicleRegNo() {
        return (String) getAttributeInternal(VEHICLEREGNO);
    }

    /**
     * Sets <code>value</code> as attribute value for VEHICLE_REG_NO using the alias name VehicleRegNo.
     * @param value value to set the VEHICLE_REG_NO
     */
    public void setVehicleRegNo(String value) {
        setAttributeInternal(VEHICLEREGNO, value);
    }

    /**
     * Gets the attribute value for VEHICLE_ID using the alias name VehicleId.
     * @return the VEHICLE_ID
     */
    public DBSequence getVehicleId() {
        return (DBSequence) getAttributeInternal(VEHICLEID);
    }

    /**
     * Sets <code>value</code> as attribute value for VEHICLE_ID using the alias name VehicleId.
     * @param value value to set the VEHICLE_ID
     */
    public void setVehicleId(DBSequence value) {
        setAttributeInternal(VEHICLEID, value);
    }

    /**
     * Gets the attribute value for VEHICLE_ID_FK using the alias name VehicleIdFk.
     * @return the VEHICLE_ID_FK
     */
    public BigDecimal getVehicleIdFk() {
        return (BigDecimal) getAttributeInternal(VEHICLEIDFK);
    }

    /**
     * Sets <code>value</code> as attribute value for VEHICLE_ID_FK using the alias name VehicleIdFk.
     * @param value value to set the VEHICLE_ID_FK
     */
    public void setVehicleIdFk(BigDecimal value) {
        setAttributeInternal(VEHICLEIDFK, value);
    }

    /**
     * Gets the attribute value for TNS_S_DATE using the alias name TnsSDate.
     * @return the TNS_S_DATE
     */
    public Timestamp getTnsSDate() {
        return (Timestamp) getAttributeInternal(TNSSDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for TNS_S_DATE using the alias name TnsSDate.
     * @param value value to set the TNS_S_DATE
     */
    public void setTnsSDate(Timestamp value) {
        setAttributeInternal(TNSSDATE, value);
    }

    /**
     * Gets the attribute value for TNS_FREIGHTFACTOR using the alias name TnsFreightfactor.
     * @return the TNS_FREIGHTFACTOR
     */
    public BigDecimal getTnsFreightfactor() {
        return (BigDecimal) getAttributeInternal(TNSFREIGHTFACTOR);
    }

    /**
     * Sets <code>value</code> as attribute value for TNS_FREIGHTFACTOR using the alias name TnsFreightfactor.
     * @param value value to set the TNS_FREIGHTFACTOR
     */
    public void setTnsFreightfactor(BigDecimal value) {
        BigDecimal InputAmount=value;
        Timestamp RDate= this.getTnsDate();
        Long productID =this.getTnsCoaCactNumber();
            productID=productID-5000000;
        String rateSTR;
        rateSTR = this.execRetailRate(productID, RDate);

        BigDecimal RateBD=new BigDecimal(rateSTR);
        MathContext mc 
                   = new MathContext(8);
        BigDecimal qty;
       
        qty = new BigDecimal(0.0, mc);
      
        qty=(BigDecimal)InputAmount.divide(RateBD, mc);
        qty=qty.setScale(8, RoundingMode.HALF_UP);
        this.setTnsQty(qty);
        this.setTnsRate(rateSTR);
        this.calculateAmount();
        setAttributeInternal(TNSFREIGHTFACTOR, value);
        
       // setAttributeInternal(TNSFREIGHTFACTOR, value);
    }


    /**
     * Gets the view accessor <code>RowSet</code> COA_PARTY_CUSTOMER_CASH1.
     */
    public RowSet getCOA_PARTY_CUSTOMER_CASH1() {
        RowSet rs1 = (RowSet)getAttributeInternal(COA_PARTY_CUSTOMER_CASH1);
          rs1.executeQuery();
          return rs1;
       // return (RowSet) getAttributeInternal(COA_PARTY_CUSTOMER_CASH1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> COAPRoductRevenue1.
     */
    public RowSet getCOAPRoductRevenue1() {
        RowSet rs1 = (RowSet)getAttributeInternal(COAPRODUCTREVENUE1);
                 rs1.executeQuery();
                 
                 return rs1;
      //  return (RowSet) getAttributeInternal(COAPRODUCTREVENUE1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> Vehicle1View1.
     */
    public RowSet getVehicle1View1() {
        RowSet rs1 = (RowSet)getAttributeInternal(VEHICLE1VIEW1);
                 rs1.executeQuery();
                 return rs1;
       // return (RowSet) getAttributeInternal(VEHICLE1VIEW1);
    }

    public void calculateAmount(){
                     
                       
                       
                        MathContext mc 
                                   = new MathContext(8);
                        BigDecimal value;
                        
                        value = new BigDecimal(0.0, mc);
                       
                       
                        BigDecimal Rate=new BigDecimal(this.getTnsRate(),mc);
                  
                      
                       
                          value=Rate.multiply(this.getTnsQty(),mc);  
                        System.out.println("amount ="+value);      
                        
                            
                        value=value.setScale(7, RoundingMode.HALF_UP);
                        setAttributeInternal(TNSAMOUNT, value);
                       setAttributeInternal(TNSFORMATAMOUNT, value);
                        String str=this.SpellAmount();
                        this.setTnsSpellAmount(str);
                       
                   
                    }
                        public String SpellAmount() {
                            String res = "ERROR"; 
                            ApplicationModule applicationModule = getApplicationModule();
                            
                            if (applicationModule instanceof VOAPPImpl){  
                                       VOAPPImpl am = (VOAPPImpl) applicationModule;  
                                      res = am.get_Spell_number(this.getTnsAmount());
                                          //pass values from current row to plsql func and get resut  
                                   }  
                            return res;
                            //return (String) getAttributeInternal(TNSSPELLAMOUNT);
                        }
        public Timestamp getSelectedDateView() {
            Timestamp res = new Timestamp(-10000);
            ApplicationModule applicationModule = getApplicationModule();
            
            if (applicationModule instanceof VOAPPImpl){  
                       VOAPPImpl am = (VOAPPImpl) applicationModule;  
                      res = am.getSelectedDate();
                          //pass values from current row to plsql func and get resut  
                   }  
            return res;
            //return (String) getAttributeInternal(TNSSPELLAMOUNT);
        }
    public String execRetailRate(Long Value, Timestamp RRDate) {
        String res ="" ;
        ApplicationModule applicationModule = getApplicationModule();
        
        if (applicationModule instanceof VOAPPImpl){
            VOAPPImpl am;
            am = (VOAPPImpl) applicationModule;
            res = am.execGetRetailRate(Value,RRDate);
               
                      //pass values from current row to plsql func and get resut  
               }  
        return res;
        //return (String) getAttributeInternal(TNSSPELLAMOUNT);
    }
                 
    }



