package model;

import java.math.BigDecimal;

import java.math.RoundingMode;

import java.sql.Timestamp;

import oracle.jbo.ApplicationModule;
import oracle.jbo.RowSet;
import oracle.jbo.domain.DBSequence;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Nov 27 00:38:08 PKT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SalesALLRowImpl extends ViewRowImpl {


    public static final int ENTITY_TRANSACTION = 0;
    public static final int ENTITY_CHARTOFACCOUNTS = 1;
    public static final int ENTITY_CHARTOFACCOUNTS1 = 2;
    public static final int ENTITY_OILTANKER = 3;
    public static final int ENTITY_SALERATELOG = 4;
    public static final int ENTITY_OILTANKER1 = 5;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        TnsId,
        TnsAmount,
        TnsQty,
        TnsNewrate,
        TnsRate,
        TnsOildId,
        TnsOiltId,
        TnsCoaDactNumber,
        TnsCoaCactNumber,
        TnsDate,
        TnsDetail,
        TnsSlipDate,
        TnsSlipNo,
        TnsTnsviewId,
        TnsTnsTypeIdFk,
        CoaName,
        CoaActNumber,
        CoaCode,
        CoaBalance,
        CoaPartyId,
        CoaName1,
        CoaActNumber1,
        CoaQtyBalance,
        CoaCode1,
        CoaBalance1,
        CoaProductId,
        OiltRegistration,
        OiltId,
        OiltCapacity,
        SaleRateLogR,
        SaleRateLogId,
        TnsSaleRateLogIdFk,
        TnsInfo,
        TnsFormatAmount,
        TnsSpellAmount,
        OiltRegistration1,
        OiltId1,
        OiltCapacity1,
        TnsStorageOiltIdFk,
        TnsSDate,
        OilTankerAllView1,
        COAPartyCustomerOnly1,
        COAPRoductRevenue1,
        SaleRateLogForCustomer1,
        OilTanker_And_Tank_Only1;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int TNSID = AttributesEnum.TnsId.index();
    public static final int TNSAMOUNT = AttributesEnum.TnsAmount.index();
    public static final int TNSQTY = AttributesEnum.TnsQty.index();
    public static final int TNSNEWRATE = AttributesEnum.TnsNewrate.index();
    public static final int TNSRATE = AttributesEnum.TnsRate.index();
    public static final int TNSOILDID = AttributesEnum.TnsOildId.index();
    public static final int TNSOILTID = AttributesEnum.TnsOiltId.index();
    public static final int TNSCOADACTNUMBER = AttributesEnum.TnsCoaDactNumber.index();
    public static final int TNSCOACACTNUMBER = AttributesEnum.TnsCoaCactNumber.index();
    public static final int TNSDATE = AttributesEnum.TnsDate.index();
    public static final int TNSDETAIL = AttributesEnum.TnsDetail.index();
    public static final int TNSSLIPDATE = AttributesEnum.TnsSlipDate.index();
    public static final int TNSSLIPNO = AttributesEnum.TnsSlipNo.index();
    public static final int TNSTNSVIEWID = AttributesEnum.TnsTnsviewId.index();
    public static final int TNSTNSTYPEIDFK = AttributesEnum.TnsTnsTypeIdFk.index();
    public static final int COANAME = AttributesEnum.CoaName.index();
    public static final int COAACTNUMBER = AttributesEnum.CoaActNumber.index();
    public static final int COACODE = AttributesEnum.CoaCode.index();
    public static final int COABALANCE = AttributesEnum.CoaBalance.index();
    public static final int COAPARTYID = AttributesEnum.CoaPartyId.index();
    public static final int COANAME1 = AttributesEnum.CoaName1.index();
    public static final int COAACTNUMBER1 = AttributesEnum.CoaActNumber1.index();
    public static final int COAQTYBALANCE = AttributesEnum.CoaQtyBalance.index();
    public static final int COACODE1 = AttributesEnum.CoaCode1.index();
    public static final int COABALANCE1 = AttributesEnum.CoaBalance1.index();
    public static final int COAPRODUCTID = AttributesEnum.CoaProductId.index();
    public static final int OILTREGISTRATION = AttributesEnum.OiltRegistration.index();
    public static final int OILTID = AttributesEnum.OiltId.index();
    public static final int OILTCAPACITY = AttributesEnum.OiltCapacity.index();
    public static final int SALERATELOGR = AttributesEnum.SaleRateLogR.index();
    public static final int SALERATELOGID = AttributesEnum.SaleRateLogId.index();
    public static final int TNSSALERATELOGIDFK = AttributesEnum.TnsSaleRateLogIdFk.index();
    public static final int TNSINFO = AttributesEnum.TnsInfo.index();
    public static final int TNSFORMATAMOUNT = AttributesEnum.TnsFormatAmount.index();
    public static final int TNSSPELLAMOUNT = AttributesEnum.TnsSpellAmount.index();
    public static final int OILTREGISTRATION1 = AttributesEnum.OiltRegistration1.index();
    public static final int OILTID1 = AttributesEnum.OiltId1.index();
    public static final int OILTCAPACITY1 = AttributesEnum.OiltCapacity1.index();
    public static final int TNSSTORAGEOILTIDFK = AttributesEnum.TnsStorageOiltIdFk.index();
    public static final int TNSSDATE = AttributesEnum.TnsSDate.index();
    public static final int OILTANKERALLVIEW1 = AttributesEnum.OilTankerAllView1.index();
    public static final int COAPARTYCUSTOMERONLY1 = AttributesEnum.COAPartyCustomerOnly1.index();
    public static final int COAPRODUCTREVENUE1 = AttributesEnum.COAPRoductRevenue1.index();
    public static final int SALERATELOGFORCUSTOMER1 = AttributesEnum.SaleRateLogForCustomer1.index();
    public static final int OILTANKER_AND_TANK_ONLY1 = AttributesEnum.OilTanker_And_Tank_Only1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public SalesALLRowImpl() {
    }

    /**
     * Gets Transaction entity object.
     * @return the Transaction
     */
    public TransactionImpl getTransaction() {
        return (TransactionImpl) getEntity(ENTITY_TRANSACTION);
    }

    /**
     * Gets ChartOfAccounts entity object.
     * @return the ChartOfAccounts
     */
    public EntityImpl getChartOfAccounts() {
        return (EntityImpl) getEntity(ENTITY_CHARTOFACCOUNTS);
    }

    /**
     * Gets ChartOfAccounts1 entity object.
     * @return the ChartOfAccounts1
     */
    public EntityImpl getChartOfAccounts1() {
        return (EntityImpl) getEntity(ENTITY_CHARTOFACCOUNTS1);
    }

    /**
     * Gets OilTanker entity object.
     * @return the OilTanker
     */
    public EntityImpl getOilTanker() {
        return (EntityImpl) getEntity(ENTITY_OILTANKER);
    }


    /**
     * Gets SaleRateLog entity object.
     * @return the SaleRateLog
     */
    public EntityImpl getSaleRateLog() {
        return (EntityImpl) getEntity(ENTITY_SALERATELOG);
    }


    /**
     * Gets OilTanker1 entity object.
     * @return the OilTanker1
     */
    public EntityImpl getOilTanker1() {
        return (EntityImpl) getEntity(ENTITY_OILTANKER1);
    }

    /**
     * Gets the attribute value for TNS_ID using the alias name TnsId.
     * @return the TNS_ID
     */
    public DBSequence getTnsId() {
        return (DBSequence) getAttributeInternal(TNSID);
    }


    /**
     * Gets the attribute value for TNS_AMOUNT using the alias name TnsAmount.
     * @return the TNS_AMOUNT
     */
    public BigDecimal getTnsAmount() {
        return (BigDecimal) getAttributeInternal(TNSAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for TNS_AMOUNT using the alias name TnsAmount.
     * @param value value to set the TNS_AMOUNT
     */
    public void setTnsAmount(BigDecimal value) {
        setAttributeInternal(TNSAMOUNT, value);
    }


    /**
     * Gets the attribute value for TNS_QTY using the alias name TnsQty.
     * @return the TNS_QTY
     */
    public BigDecimal getTnsQty() {
        return (BigDecimal) getAttributeInternal(TNSQTY);
    }


    /**
     * Sets <code>value</code> as attribute value for TNS_QTY using the alias name TnsQty.
     * @param value value to set the TNS_QTY
     */
    public void setTnsQty(BigDecimal value) {
        setAttributeInternal(TNSQTY, value);
        this.calculateAmount();
    }

    /**
     * Gets the attribute value for TNS_NEWRATE using the alias name TnsNewrate.
     * @return the TNS_NEWRATE
     */
    public String getTnsNewrate() {
        
        return (String) getAttributeInternal(TNSNEWRATE);
    }


    /**
     * Sets <code>value</code> as attribute value for TNS_NEWRATE using the alias name TnsNewrate.
     * @param value value to set the TNS_NEWRATE
     */
    public void setTnsNewrate(String value) {
        setAttributeInternal(TNSNEWRATE, value);
        this.calculateAmount();
    }

    /**
     * Gets the attribute value for TNS_RATE using the alias name TnsRate.
     * @return the TNS_RATE
     */
    public String getTnsRate() {
        return (String) getAttributeInternal(TNSRATE);
    }

    /**
     * Sets <code>value</code> as attribute value for TNS_RATE using the alias name TnsRate.
     * @param value value to set the TNS_RATE
     */
    public void setTnsRate(String value) {
        setAttributeInternal(TNSRATE, value);
        this.calculateAmount();
    }

    /**
     * Gets the attribute value for TNS_OILD_ID using the alias name TnsOildId.
     * @return the TNS_OILD_ID
     */
    public Long getTnsOildId() {
        return (Long) getAttributeInternal(TNSOILDID);
    }

    /**
     * Sets <code>value</code> as attribute value for TNS_OILD_ID using the alias name TnsOildId.
     * @param value value to set the TNS_OILD_ID
     */
    public void setTnsOildId(Long value) {
        setAttributeInternal(TNSOILDID, value);
    }

    /**
     * Gets the attribute value for TNS_OILT_ID using the alias name TnsOiltId.
     * @return the TNS_OILT_ID
     */
    public Long getTnsOiltId() {
        return (Long) getAttributeInternal(TNSOILTID);
    }

    /**
     * Sets <code>value</code> as attribute value for TNS_OILT_ID using the alias name TnsOiltId.
     * @param value value to set the TNS_OILT_ID
     */
    public void setTnsOiltId(Long value) {
        setAttributeInternal(TNSOILTID, value);
    }

    /**
     * Gets the attribute value for TNS_COA_DACT_NUMBER using the alias name TnsCoaDactNumber.
     * @return the TNS_COA_DACT_NUMBER
     */
    public Long getTnsCoaDactNumber() {
        return (Long) getAttributeInternal(TNSCOADACTNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for TNS_COA_DACT_NUMBER using the alias name TnsCoaDactNumber.
     * @param value value to set the TNS_COA_DACT_NUMBER
     */
    public void setTnsCoaDactNumber(Long value) {
        setAttributeInternal(TNSCOADACTNUMBER, value);
    }

    /**
     * Gets the attribute value for TNS_COA_CACT_NUMBER using the alias name TnsCoaCactNumber.
     * @return the TNS_COA_CACT_NUMBER
     */
    public Long getTnsCoaCactNumber() {
        return (Long) getAttributeInternal(TNSCOACACTNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for TNS_COA_CACT_NUMBER using the alias name TnsCoaCactNumber.
     * @param value value to set the TNS_COA_CACT_NUMBER
     */
    public void setTnsCoaCactNumber(Long value) {
        setAttributeInternal(TNSCOACACTNUMBER, value);
    }

    /**
     * Gets the attribute value for TNS_DATE using the alias name TnsDate.
     * @return the TNS_DATE
     */
    public Timestamp getTnsDate() {
        return (Timestamp) getAttributeInternal(TNSDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for TNS_DATE using the alias name TnsDate.
     * @param value value to set the TNS_DATE
     */
    public void setTnsDate(Timestamp value) {
        setAttributeInternal(TNSDATE, value);
    }

    /**
     * Gets the attribute value for TNS_DETAIL using the alias name TnsDetail.
     * @return the TNS_DETAIL
     */
    public String getTnsDetail() {
        return (String) getAttributeInternal(TNSDETAIL);
    }

    /**
     * Gets the attribute value for TNS_SLIP_DATE using the alias name TnsSlipDate.
     * @return the TNS_SLIP_DATE
     */
    public Timestamp getTnsSlipDate() {
        return (Timestamp) getAttributeInternal(TNSSLIPDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for TNS_SLIP_DATE using the alias name TnsSlipDate.
     * @param value value to set the TNS_SLIP_DATE
     */
    public void setTnsSlipDate(Timestamp value) {
        setAttributeInternal(TNSSLIPDATE, value);
    }

    /**
     * Gets the attribute value for TNS_SLIP_NO using the alias name TnsSlipNo.
     * @return the TNS_SLIP_NO
     */
    public String getTnsSlipNo() {
        return (String) getAttributeInternal(TNSSLIPNO);
    }

    /**
     * Sets <code>value</code> as attribute value for TNS_SLIP_NO using the alias name TnsSlipNo.
     * @param value value to set the TNS_SLIP_NO
     */
    public void setTnsSlipNo(String value) {
        setAttributeInternal(TNSSLIPNO, value);
    }

    /**
     * Gets the attribute value for TNS_TNSVIEW_ID using the alias name TnsTnsviewId.
     * @return the TNS_TNSVIEW_ID
     */
    public Long getTnsTnsviewId() {
        return (Long) getAttributeInternal(TNSTNSVIEWID);
    }

    /**
     * Gets the attribute value for TNS_TNS_TYPE_ID_FK using the alias name TnsTnsTypeIdFk.
     * @return the TNS_TNS_TYPE_ID_FK
     */
    public Long getTnsTnsTypeIdFk() {
        return (Long) getAttributeInternal(TNSTNSTYPEIDFK);
    }

    /**
     * Gets the attribute value for COA_NAME using the alias name CoaName.
     * @return the COA_NAME
     */
    public String getCoaName() {
        return (String) getAttributeInternal(COANAME);
    }

    /**
     * Sets <code>value</code> as attribute value for COA_NAME using the alias name CoaName.
     * @param value value to set the COA_NAME
     */
    public void setCoaName(String value) {
        setAttributeInternal(COANAME, value);
    }

    /**
     * Gets the attribute value for COA_ACT_NUMBER using the alias name CoaActNumber.
     * @return the COA_ACT_NUMBER
     */
    public Long getCoaActNumber() {
        return (Long) getAttributeInternal(COAACTNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for COA_ACT_NUMBER using the alias name CoaActNumber.
     * @param value value to set the COA_ACT_NUMBER
     */
    public void setCoaActNumber(Long value) {
        setAttributeInternal(COAACTNUMBER, value);
    }

    /**
     * Gets the attribute value for COA_CODE using the alias name CoaCode.
     * @return the COA_CODE
     */
    public Long getCoaCode() {
        return (Long) getAttributeInternal(COACODE);
    }

    /**
     * Sets <code>value</code> as attribute value for COA_CODE using the alias name CoaCode.
     * @param value value to set the COA_CODE
     */
    public void setCoaCode(Long value) {
        setAttributeInternal(COACODE, value);
    }

    /**
     * Gets the attribute value for COA_BALANCE using the alias name CoaBalance.
     * @return the COA_BALANCE
     */
    public BigDecimal getCoaBalance() {
        return (BigDecimal) getAttributeInternal(COABALANCE);
    }

    /**
     * Gets the attribute value for COA_PARTY_ID using the alias name CoaPartyId.
     * @return the COA_PARTY_ID
     */
    public Long getCoaPartyId() {
        return (Long) getAttributeInternal(COAPARTYID);
    }

    /**
     * Sets <code>value</code> as attribute value for COA_PARTY_ID using the alias name CoaPartyId.
     * @param value value to set the COA_PARTY_ID
     */
    public void setCoaPartyId(Long value) {
        setAttributeInternal(COAPARTYID, value);
    }

    /**
     * Gets the attribute value for COA_NAME using the alias name CoaName1.
     * @return the COA_NAME
     */
    public String getCoaName1() {
        return (String) getAttributeInternal(COANAME1);
    }

    /**
     * Sets <code>value</code> as attribute value for COA_NAME using the alias name CoaName1.
     * @param value value to set the COA_NAME
     */
    public void setCoaName1(String value) {
        setAttributeInternal(COANAME1, value);
    }

    /**
     * Gets the attribute value for COA_ACT_NUMBER using the alias name CoaActNumber1.
     * @return the COA_ACT_NUMBER
     */
    public Long getCoaActNumber1() {
        return (Long) getAttributeInternal(COAACTNUMBER1);
    }

    /**
     * Sets <code>value</code> as attribute value for COA_ACT_NUMBER using the alias name CoaActNumber1.
     * @param value value to set the COA_ACT_NUMBER
     */
    public void setCoaActNumber1(Long value) {
        setAttributeInternal(COAACTNUMBER1, value);
    }

    /**
     * Gets the attribute value for COA_QTY_BALANCE using the alias name CoaQtyBalance.
     * @return the COA_QTY_BALANCE
     */
    public Long getCoaQtyBalance() {
        return (Long) getAttributeInternal(COAQTYBALANCE);
    }

    /**
     * Sets <code>value</code> as attribute value for COA_QTY_BALANCE using the alias name CoaQtyBalance.
     * @param value value to set the COA_QTY_BALANCE
     */
    public void setCoaQtyBalance(Long value) {
        setAttributeInternal(COAQTYBALANCE, value);
    }

    /**
     * Gets the attribute value for COA_CODE using the alias name CoaCode1.
     * @return the COA_CODE
     */
    public Long getCoaCode1() {
        return (Long) getAttributeInternal(COACODE1);
    }

    /**
     * Sets <code>value</code> as attribute value for COA_CODE using the alias name CoaCode1.
     * @param value value to set the COA_CODE
     */
    public void setCoaCode1(Long value) {
        setAttributeInternal(COACODE1, value);
    }

    /**
     * Gets the attribute value for COA_BALANCE using the alias name CoaBalance1.
     * @return the COA_BALANCE
     */
    public BigDecimal getCoaBalance1() {
        return (BigDecimal) getAttributeInternal(COABALANCE1);
    }

    /**
     * Gets the attribute value for COA_PRODUCT_ID using the alias name CoaProductId.
     * @return the COA_PRODUCT_ID
     */
    public Long getCoaProductId() {
        return (Long) getAttributeInternal(COAPRODUCTID);
    }

    /**
     * Sets <code>value</code> as attribute value for COA_PRODUCT_ID using the alias name CoaProductId.
     * @param value value to set the COA_PRODUCT_ID
     */
    public void setCoaProductId(Long value) {
        setAttributeInternal(COAPRODUCTID, value);
    }

    /**
     * Gets the attribute value for OILT_REGISTRATION# using the alias name OiltRegistration.
     * @return the OILT_REGISTRATION#
     */
    public String getOiltRegistration() {
        return (String) getAttributeInternal(OILTREGISTRATION);
    }

    /**
     * Sets <code>value</code> as attribute value for OILT_REGISTRATION# using the alias name OiltRegistration.
     * @param value value to set the OILT_REGISTRATION#
     */
    public void setOiltRegistration(String value) {
        setAttributeInternal(OILTREGISTRATION, value);
    }

    /**
     * Gets the attribute value for OILT_ID using the alias name OiltId.
     * @return the OILT_ID
     */
    public DBSequence getOiltId() {
        return (DBSequence) getAttributeInternal(OILTID);
    }

    /**
     * Sets <code>value</code> as attribute value for OILT_ID using the alias name OiltId.
     * @param value value to set the OILT_ID
     */
    public void setOiltId(DBSequence value) {
        setAttributeInternal(OILTID, value);
    }

    /**
     * Gets the attribute value for OILT_CAPACITY using the alias name OiltCapacity.
     * @return the OILT_CAPACITY
     */
    public Long getOiltCapacity() {
        return (Long) getAttributeInternal(OILTCAPACITY);
    }

    /**
     * Sets <code>value</code> as attribute value for OILT_CAPACITY using the alias name OiltCapacity.
     * @param value value to set the OILT_CAPACITY
     */
    public void setOiltCapacity(Long value) {
        setAttributeInternal(OILTCAPACITY, value);
    }


    /**
     * Gets the attribute value for SALE_RATE_LOG_R using the alias name SaleRateLogR.
     * @return the SALE_RATE_LOG_R
     */
    public String getSaleRateLogR() {
        return (String) getAttributeInternal(SALERATELOGR);
    }

    /**
     * Sets <code>value</code> as attribute value for SALE_RATE_LOG_R using the alias name SaleRateLogR.
     * @param value value to set the SALE_RATE_LOG_R
     */
    public void setSaleRateLogR(String value) {
        setAttributeInternal(SALERATELOGR, value);
    }

    /**
     * Gets the attribute value for SALE_RATE_LOG_ID using the alias name SaleRateLogId.
     * @return the SALE_RATE_LOG_ID
     */
    public DBSequence getSaleRateLogId() {
        return (DBSequence) getAttributeInternal(SALERATELOGID);
    }

    /**
     * Sets <code>value</code> as attribute value for SALE_RATE_LOG_ID using the alias name SaleRateLogId.
     * @param value value to set the SALE_RATE_LOG_ID
     */
    public void setSaleRateLogId(DBSequence value) {
        setAttributeInternal(SALERATELOGID, value);
    }

    /**
     * Gets the attribute value for TNS_SALE_RATE_LOG_ID_FK using the alias name TnsSaleRateLogIdFk.
     * @return the TNS_SALE_RATE_LOG_ID_FK
     */
    public Long getTnsSaleRateLogIdFk() {
        return (Long) getAttributeInternal(TNSSALERATELOGIDFK);
    }

    /**
     * Sets <code>value</code> as attribute value for TNS_SALE_RATE_LOG_ID_FK using the alias name TnsSaleRateLogIdFk.
     * @param value value to set the TNS_SALE_RATE_LOG_ID_FK
     */
    public void setTnsSaleRateLogIdFk(Long value) {
        setAttributeInternal(TNSSALERATELOGIDFK, value);
    }


    /**
     * Gets the attribute value for TNS_INFO using the alias name TnsInfo.
     * @return the TNS_INFO
     */
    public String getTnsInfo() {
        return (String) getAttributeInternal(TNSINFO);
    }

    /**
     * Sets <code>value</code> as attribute value for TNS_INFO using the alias name TnsInfo.
     * @param value value to set the TNS_INFO
     */
    public void setTnsInfo(String value) {
        setAttributeInternal(TNSINFO, value);
    }

    /**
     * Gets the attribute value for TNS_FORMAT_AMOUNT using the alias name TnsFormatAmount.
     * @return the TNS_FORMAT_AMOUNT
     */
    public BigDecimal getTnsFormatAmount() {
        return (BigDecimal) getAttributeInternal(TNSAMOUNT);
      //  return (BigDecimal) getAttributeInternal(TNSFORMATAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for TNS_FORMAT_AMOUNT using the alias name TnsFormatAmount.
     * @param value value to set the TNS_FORMAT_AMOUNT
     */
    public void setTnsFormatAmount(BigDecimal value) {
        value=(BigDecimal)this.getAttributeInternal(TNSAMOUNT);
            setAttributeInternal(TNSFORMATAMOUNT, value);
        }
     

    /**
     * Gets the attribute value for TNS_SPELL_AMOUNT using the alias name TnsSpellAmount.
     * @return the TNS_SPELL_AMOUNT
     */
    public String getTnsSpellAmount() {
        return this.SpellAmount();
     //   return (String) getAttributeInternal(TNSSPELLAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for TNS_SPELL_AMOUNT using the alias name TnsSpellAmount.
     * @param value value to set the TNS_SPELL_AMOUNT
     */
    public void setTnsSpellAmount(String value) {
        
       setAttributeInternal(TNSSPELLAMOUNT, value);
    }

    /**
     * Gets the attribute value for OILT_REGISTRATION# using the alias name OiltRegistration1.
     * @return the OILT_REGISTRATION#
     */
    public String getOiltRegistration1() {
        return (String) getAttributeInternal(OILTREGISTRATION1);
    }

    /**
     * Sets <code>value</code> as attribute value for OILT_REGISTRATION# using the alias name OiltRegistration1.
     * @param value value to set the OILT_REGISTRATION#
     */
    public void setOiltRegistration1(String value) {
        setAttributeInternal(OILTREGISTRATION1, value);
    }

    /**
     * Gets the attribute value for OILT_ID using the alias name OiltId1.
     * @return the OILT_ID
     */
    public DBSequence getOiltId1() {
        return (DBSequence) getAttributeInternal(OILTID1);
    }

    /**
     * Sets <code>value</code> as attribute value for OILT_ID using the alias name OiltId1.
     * @param value value to set the OILT_ID
     */
    public void setOiltId1(DBSequence value) {
        setAttributeInternal(OILTID1, value);
    }

    /**
     * Gets the attribute value for OILT_CAPACITY using the alias name OiltCapacity1.
     * @return the OILT_CAPACITY
     */
    public Long getOiltCapacity1() {
        return (Long) getAttributeInternal(OILTCAPACITY1);
    }

    /**
     * Sets <code>value</code> as attribute value for OILT_CAPACITY using the alias name OiltCapacity1.
     * @param value value to set the OILT_CAPACITY
     */
    public void setOiltCapacity1(Long value) {
        setAttributeInternal(OILTCAPACITY1, value);
    }

    /**
     * Gets the attribute value for TNS_STORAGE_OILT_ID_FK using the alias name TnsStorageOiltIdFk.
     * @return the TNS_STORAGE_OILT_ID_FK
     */
    public Long getTnsStorageOiltIdFk() {
        return (Long) getAttributeInternal(TNSSTORAGEOILTIDFK);
    }

    /**
     * Sets <code>value</code> as attribute value for TNS_STORAGE_OILT_ID_FK using the alias name TnsStorageOiltIdFk.
     * @param value value to set the TNS_STORAGE_OILT_ID_FK
     */
    public void setTnsStorageOiltIdFk(Long value) {
        setAttributeInternal(TNSSTORAGEOILTIDFK, value);
    }

    /**
     * Gets the attribute value for TNS_S_DATE using the alias name TnsSDate.
     * @return the TNS_S_DATE
     */
    public Timestamp getTnsSDate() {
        return (Timestamp) getAttributeInternal(TNSSDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for TNS_S_DATE using the alias name TnsSDate.
     * @param value value to set the TNS_S_DATE
     */
    public void setTnsSDate(Timestamp value) {
        setAttributeInternal(TNSSDATE, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> OilTankerAllView1.
     */
    public RowSet getOilTankerAllView1() {
        RowSet rs1 = (RowSet)getAttributeInternal(OILTANKERALLVIEW1);
                 rs1.executeQuery();
                 return rs1;
      //  return (RowSet) getAttributeInternal(OILTANKERALLVIEW1);
    }


    /**
     * Gets the view accessor <code>RowSet</code> COAPartyCustomerOnly1.
     */
    public RowSet getCOAPartyCustomerOnly1() {
        RowSet rs1 = (RowSet)getAttributeInternal(COAPARTYCUSTOMERONLY1);
                 rs1.executeQuery();
                 return rs1;
      //  return (RowSet) getAttributeInternal(COAPARTYCUSTOMERONLY1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> COAPRoductRevenue1.
     */
    public RowSet getCOAPRoductRevenue1() {
        RowSet rs1 = (RowSet)getAttributeInternal(COAPRODUCTREVENUE1);
                 rs1.executeQuery();
                 return rs1;
       // return (RowSet) getAttributeInternal(COAPRODUCTREVENUE1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> SaleRateLogForCustomer1.
     */
    public RowSet getSaleRateLogForCustomer1() {
        RowSet rs1 = (RowSet)getAttributeInternal(SALERATELOGFORCUSTOMER1);
                 rs1.executeQuery();
                 return rs1;
       // return (RowSet) getAttributeInternal(SALERATELOGFORCUSTOMER1);
    }


    /**
     * Gets the view accessor <code>RowSet</code> OilTanker_And_Tank_Only1.
     */
    public RowSet getOilTanker_And_Tank_Only1() {
        RowSet rs1 = (RowSet)getAttributeInternal(OILTANKER_AND_TANK_ONLY1);
                 rs1.executeQuery();
                 return rs1;
     //   return (RowSet) getAttributeInternal(OILTANKER_AND_TANK_ONLY1);
    }

    public void calculateAmount(){
          BigDecimal value;
          BigDecimal temp=new BigDecimal(0);
          BigDecimal NewRate=new BigDecimal(this.getTnsNewrate());
          BigDecimal Rate=new BigDecimal(this.getTnsRate());
          
          int res=temp.compareTo(NewRate);
          if(res==0){
            value=Rate.multiply(this.getTnsQty());  
             
          }else{
              value=NewRate.multiply(this.getTnsQty());
              
          }
          
              
          value=value.setScale(5, RoundingMode.HALF_UP);
          setAttributeInternal(TNSAMOUNT, value);
         // setAttributeInternal(TNSFORMATAMOUNT, value);
        //  String str=this.SpellAmount();
         // this.setTnsSpellAmount(str);
         
      }
          public String SpellAmount() {
              String res = "ERROR"; 
              ApplicationModule applicationModule = getApplicationModule();
              
              if (applicationModule instanceof VOAPPImpl){  
                         VOAPPImpl am = (VOAPPImpl) applicationModule;  
                        res = am.get_Spell_number(this.getTnsAmount());
                            //pass values from current row to plsql func and get resut  
                     }  
              return res;
              //return (String) getAttributeInternal(TNSSPELLAMOUNT);
          }
      }



