package model;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Apr 16 14:45:36 PKT 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class Sum_detail_viewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public Sum_detail_viewImpl() {
    }
}

