package model;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Feb 18 13:16:42 PKT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TestTruncDateViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public TestTruncDateViewImpl() {
    }
}

