package model;

import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Dec 20 13:57:28 PKT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class YESNOViewObjRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        YESNO_ID,
        YES_NO_VALUE;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return YESNOViewObjRowImpl.AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return YESNOViewObjRowImpl.AttributesEnum.firstIndex() + YESNOViewObjRowImpl.AttributesEnum
                                                                                        .staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = YESNOViewObjRowImpl.AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int YESNO_ID = AttributesEnum.YESNO_ID.index();
    public static final int YES_NO_VALUE = AttributesEnum.YES_NO_VALUE.index();

    /**
     * This is the default constructor (do not remove).
     */
    public YESNOViewObjRowImpl() {
    }
}

