package model;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Dec 20 13:57:29 PKT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class YESNOViewObjImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public YESNOViewObjImpl() {
    }
}

