package model;

import java.sql.Timestamp;

import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Oct 30 12:27:11 PKT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ZRptTbParamViewRowImpl extends ViewRowImpl {


    public static final int ENTITY_ZRPTTBPARAM = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        ZRptTbParamId,
        ZRptTbParamDate,
        ZRptTbParamTbio,
        ZRptTbTotalView,
        ZRptTbView,
        TBInputOption1;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ZRPTTBPARAMID = AttributesEnum.ZRptTbParamId.index();
    public static final int ZRPTTBPARAMDATE = AttributesEnum.ZRptTbParamDate.index();
    public static final int ZRPTTBPARAMTBIO = AttributesEnum.ZRptTbParamTbio.index();
    public static final int ZRPTTBTOTALVIEW = AttributesEnum.ZRptTbTotalView.index();
    public static final int ZRPTTBVIEW = AttributesEnum.ZRptTbView.index();
    public static final int TBINPUTOPTION1 = AttributesEnum.TBInputOption1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ZRptTbParamViewRowImpl() {
    }

    /**
     * Gets ZRptTbParam entity object.
     * @return the ZRptTbParam
     */
    public EntityImpl getZRptTbParam() {
        return (EntityImpl) getEntity(ENTITY_ZRPTTBPARAM);
    }

    /**
     * Gets the attribute value for Z_RPT_TB_PARAM_ID using the alias name ZRptTbParamId.
     * @return the Z_RPT_TB_PARAM_ID
     */
    public Long getZRptTbParamId() {
        return (Long) getAttributeInternal(ZRPTTBPARAMID);
    }

    /**
     * Sets <code>value</code> as attribute value for Z_RPT_TB_PARAM_ID using the alias name ZRptTbParamId.
     * @param value value to set the Z_RPT_TB_PARAM_ID
     */
    public void setZRptTbParamId(Long value) {
        setAttributeInternal(ZRPTTBPARAMID, value);
    }

    /**
     * Gets the attribute value for Z_RPT_TB_PARAM_DATE using the alias name ZRptTbParamDate.
     * @return the Z_RPT_TB_PARAM_DATE
     */
    public Timestamp getZRptTbParamDate() {
        return (Timestamp) getAttributeInternal(ZRPTTBPARAMDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for Z_RPT_TB_PARAM_DATE using the alias name ZRptTbParamDate.
     * @param value value to set the Z_RPT_TB_PARAM_DATE
     */
    public void setZRptTbParamDate(Timestamp value) {
        setAttributeInternal(ZRPTTBPARAMDATE, value);
    }

    /**
     * Gets the attribute value for Z_RPT_TB_PARAM_TBIO using the alias name ZRptTbParamTbio.
     * @return the Z_RPT_TB_PARAM_TBIO
     */
    public Long getZRptTbParamTbio() {
        return (Long) getAttributeInternal(ZRPTTBPARAMTBIO);
    }

    /**
     * Sets <code>value</code> as attribute value for Z_RPT_TB_PARAM_TBIO using the alias name ZRptTbParamTbio.
     * @param value value to set the Z_RPT_TB_PARAM_TBIO
     */
    public void setZRptTbParamTbio(Long value) {
        setAttributeInternal(ZRPTTBPARAMTBIO, value);
    }


    /**
     * Gets the associated <code>RowIterator</code> using master-detail link ZRptTbTotalView.
     */
    public RowIterator getZRptTbTotalView() {
        return (RowIterator) getAttributeInternal(ZRPTTBTOTALVIEW);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link ZRptTbView.
     */
    public RowIterator getZRptTbView() {
        return (RowIterator) getAttributeInternal(ZRPTTBVIEW);
    }

    /**
     * Gets the view accessor <code>RowSet</code> TBInputOption1.
     */
    public RowSet getTBInputOption1() {
        return (RowSet) getAttributeInternal(TBINPUTOPTION1);
    }


}

